import { describe, expect, it } from "vitest";

import { isAutoGeneratedBlogPost } from "./blog-utils";
import type { BlogPost } from "@/types";

function post(overrides: Partial<BlogPost> = {}): BlogPost {
  return {
    id: "test",
    slug: "test",
    title: "Поездка по Патагонии",
    excerpt: "Практический маршрут для самостоятельной поездки.",
    content: "Проверяйте погоду и расписание перед выездом.",
    author: "Редакция",
    date: "2026-07-01",
    image: "/images/test.jpg",
    category: "Путешествия",
    readTime: "5 мин",
    readTimeMinutes: 5,
    tags: [],
    ...overrides,
  };
}

describe("blog publication quarantine", () => {
  it("keeps edited Russian articles public", () => {
    expect(isAutoGeneratedBlogPost(post())).toBe(false);
  });

  it("quarantines explicit drafts", () => {
    expect(isAutoGeneratedBlogPost(post({ noIndex: true }))).toBe(true);
  });

  it("quarantines machine-import language leaks", () => {
    expect(
      isAutoGeneratedBlogPost(
        post({ content: "Добавьте buffer day и скачайте offline maps." }),
      ),
    ).toBe(true);
  });

  it("quarantines unverified legal and financial guides", () => {
    expect(isAutoGeneratedBlogPost(post({ slug: "argentina-tourist-visa-2026" }))).toBe(true);
    expect(isAutoGeneratedBlogPost(post({ slug: "blue-dollar-argentina-2026" }))).toBe(true);
  });
});
