import { describe, expect, it } from "vitest";
import { blogPosts } from "@/data/blog";
import { blogPostsFromCmsDocuments } from "@/lib/cms/cms-cutover";
import { filterIndexableBlogPosts, filterPublicBlogCatalog, isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import type { CmsDocument } from "@/types/cms-content";

describe("public blog catalog", () => {
  it("TS catalog has auto-generated drafts separated from indexable posts", () => {
    const indexable = filterIndexableBlogPosts(blogPosts);
    expect(indexable.length).toBeGreaterThan(0);
    expect(indexable.length).toBeLessThan(blogPosts.length);
    expect(indexable.every((post) => !isAutoGeneratedBlogPost(post))).toBe(true);
  });

  it("CMS documents inherit noIndex from TS fallback and are filtered out", () => {
    const autoSlug = blogPosts.find(isAutoGeneratedBlogPost)?.slug;
    expect(autoSlug).toBeTruthy();
    if (!autoSlug) return;

    const doc: CmsDocument = {
      id: `blog:${autoSlug}:ru`,
      docType: "blog",
      slug: autoSlug,
      locale: "ru",
      status: "published",
      title: "Auto draft",
      updatedAt: "2026-06-01T00:00:00.000Z",
      publishedAt: "2026-06-01T00:00:00.000Z",
      scheduledPublishAt: null,
      createdBy: null,
      updatedBy: null,
      createdAt: "2026-01-01T00:00:00.000Z",
      seo: { title: "Auto draft" },
      body: {
        kind: "blog",
        excerpt: "Draft",
        content: "Draft body with enough words to pass completeness checks easily.",
        sections: [{ title: "Intro", body: "Draft section body." }],
      },
    };

    const merged = blogPostsFromCmsDocuments([doc]);
    expect(merged[0]?.noIndex).toBe(true);

    const publicCatalog = filterPublicBlogCatalog(merged);
    expect(publicCatalog).toHaveLength(0);
  });
});
