import { describe, expect, it } from "vitest";
import {
  blogPosts,
  getBlogPostBySlug,
  getBlogStartHerePosts,
  getEditorialBlogPosts,
} from "@/data/blog";
import { blogPostsFromCmsDocuments } from "@/lib/cms/cms-cutover";
import { filterIndexableBlogPosts, filterPublicBlogCatalog, isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import type { CmsDocument } from "@/types/cms-content";
import { generateBlogPostFromPlan } from "@/lib/blog-from-plan";
import { BLOG_CONTENT_PLAN } from "@/data/blog-content-plan";
import { isEditorialOverridePublicationReady } from "@/data/blog-editorial/types";
import { EDITORIAL_OVERRIDES, getEditorialOverride } from "@/data/blog-editorial";
import { getBlogEditorialIssues } from "@/lib/blog-editorial-readiness";
import fs from "node:fs";
import path from "node:path";

describe("public blog catalog", () => {
  it("keeps the reviewed catalog available when CMS cutover is unavailable or incomplete", () => {
    const resolver = fs.readFileSync(
      path.join(process.cwd(), "src/lib/cms/blog-resolver.ts"),
      "utf8",
    );
    const contentResolver = fs.readFileSync(
      path.join(process.cwd(), "src/lib/cms/content-resolver.ts"),
      "utf8",
    );

    expect(resolver).toContain("if (!supabase) return fallback");
    expect(resolver).toContain(
      "fallback.every((post) => cutoverSlugs.has(post.slug))",
    );
    expect(resolver).toContain("preservesPublishedCatalog ? cutoverCatalog : fallback");
    expect(resolver).toContain("const publicCatalog = await resolveBlogCatalog(locale)");
    expect(resolver).toContain("areBlogSlugsEquivalent(slug, post.slug)");
    expect(contentResolver).toContain("CMS_CUTOVER_CATALOG_QUERY_TIMEOUT_MS = 8_000");
  });

  it("TS catalog has auto-generated drafts separated from indexable posts", () => {
    const indexable = filterIndexableBlogPosts(blogPosts);
    expect(indexable.length).toBeGreaterThan(0);
    expect(indexable.length).toBeLessThan(blogPosts.length);
    expect(indexable.every((post) => !isAutoGeneratedBlogPost(post))).toBe(true);
  });

  it("CMS documents inherit noIndex from TS fallback and are filtered out", () => {
    const autoSlug = blogPosts.find(isAutoGeneratedBlogPost)?.slug;
    expect(autoSlug).toBeTruthy();
    if (!autoSlug) return;

    const doc: CmsDocument = {
      id: `blog:${autoSlug}:ru`,
      docType: "blog",
      slug: autoSlug,
      locale: "ru",
      status: "published",
      title: "Auto draft",
      updatedAt: "2026-06-01T00:00:00.000Z",
      publishedAt: "2026-06-01T00:00:00.000Z",
      scheduledPublishAt: null,
      createdBy: null,
      updatedBy: null,
      rowVersion: 1,
      createdAt: "2026-01-01T00:00:00.000Z",
      seo: { title: "Auto draft" },
      body: {
        kind: "blog",
        excerpt: "Draft",
        content: "Draft body with enough words to pass completeness checks easily.",
        sections: [{ title: "Intro", body: "Draft section body." }],
      },
    };

    const merged = blogPostsFromCmsDocuments([doc]);
    expect(merged[0]?.noIndex).toBe(true);

    const publicCatalog = filterPublicBlogCatalog(merged);
    expect(publicCatalog).toHaveLength(0);
  });

  it("supports fail-closed editorial quarantine without exposing the internal reason", () => {
    const item = BLOG_CONTENT_PLAN.find((candidate) => candidate.slug === "money-бюджет");
    expect(item).toBeTruthy();
    if (!item) return;

    const generated = generateBlogPostFromPlan(item, 0);
    expect(generated.noIndex).toBe(false);
    expect(JSON.stringify(generated)).not.toContain("publicationBlockReason");
    expect(
      isEditorialOverridePublicationReady({
        sections: [],
        publicationReady: false,
        publicationBlockReason: "Dynamic price snapshot is missing",
      }),
    ).toBe(false);
  });

  it("allows a source-owned override to graduate from the default quarantine", () => {
    expect(getEditorialOverride("money-бюджет")?.publicationReady).toBe(true);
    expect(getEditorialOverride("money-бюджет")?.publicationBlockReason).toBeUndefined();
    expect(getEditorialOverride("money-карты")?.publicationReady).toBe(false);
    expect(getEditorialOverride("money-карты")?.publicationBlockReason).toBeTruthy();
  });

  it("never assigns a post-cutover publication date to generated editorial posts", () => {
    const lastItem = BLOG_CONTENT_PLAN.at(-1);
    expect(lastItem).toBeTruthy();
    if (!lastItem) return;

    expect(generateBlogPostFromPlan(lastItem, BLOG_CONTENT_PLAN.length - 1).date).toBe(
      "2026-07-17",
    );
  });

  it("keeps the fixed start-here collection inside the public catalog", () => {
    expect(getBlogStartHerePosts()).toHaveLength(8);
    expect(getBlogStartHerePosts().every((post) => post.noIndex !== true)).toBe(true);
  });

  it("publishes the reviewed legacy travel set but keeps the unsafe currency article closed", () => {
    const reviewedSlugs = [
      "patagonia-авиабилеты",
      "iguazu-за-3-дня",
      "argentina-tourist-visa-2026",
      "patagoniya-marshrut-14-dney",
      "itinerary-ошибки",
      "itinerary-за-10-дней",
      "itinerary-за-14-дней",
      "itinerary-чек-лист",
      "wildlife-с-гидом",
    ];

    for (const slug of reviewedSlugs) {
      const post = getBlogPostBySlug(slug);
      expect(post?.noIndex, slug).not.toBe(true);
      expect(post?.dateModified, slug).toBe("2026-07-17");
      expect(post?.content, slug).toContain("Проверено 17.07.2026");
    }

    expect(getBlogPostBySlug("blue-dollar-argentina-2026")?.noIndex).toBe(true);
  });

  it("publishes the five source-owned manual articles with dated official provenance", () => {
    const reviewedSlugs = [
      "byudzhet-poezdki-argentina",
      "stoimost-zhizni-buenos-aires",
      "kak-menyat-dengi-argentina",
      "dni-cuil-argentina",
      "bankovskij-schet-argentina",
    ];

    for (const slug of reviewedSlugs) {
      const post = getBlogPostBySlug(slug);
      expect(post, slug).toBeDefined();
      expect(post?.noIndex, slug).not.toBe(true);
      expect(post?.dateModified, slug).toBe("2026-07-17");
      expect(post?.sections?.at(-1)?.body, slug).toContain("Проверено 17.07.2026");
      expect(getBlogEditorialIssues(post!), slug).toEqual([]);
    }
  });

  it("keeps more than 90 percent of the authored editorial set publication-ready", () => {
    const manualPosts = getEditorialBlogPosts();
    const overrides = Object.values(EDITORIAL_OVERRIDES);
    const ready =
      manualPosts.filter((post) => post.noIndex !== true).length +
      overrides.filter(isEditorialOverridePublicationReady).length;
    const total = manualPosts.length + overrides.length;

    expect({ ready, total }).toEqual({ ready: 79, total: 87 });
    expect((ready / total) * 100).toBeGreaterThan(90);
  });
});
