import { SITE_SUPPORT_EMAIL } from "@/data/site-support-email";
import { buildTripsterIguazuDemoOperations } from "@/data/trip-operations-seeds";
import { guestUserIdFromEmail } from "@/lib/guest-booking";
import { tourCover } from "@/lib/seed-media";
import type { Booking } from "@/types/tourist";

/** Isolated local-demo provider, selected by the build alias only. */
export function getDemoBookingSeeds(now: string): Booking[] {
  return [
    {
      id: "booking-demo-new",
      userId: "ivan-evdokimychev",
      organizerTourId: "org-iguazu",
      tourId: "4",
      tourSlug: "iguazu-falls",
      tourTitle: "Водопады Игуасу за 1 день: аргентинская и бразильская стороны",
      tourImage: tourCover("iguazu-falls"),
      status: "new",
      guests: 2,
      startDate: "2026-09-12",
      endDate: "2026-09-13",
      totalPriceUsd: 1180,
      contactName: "Иван Евдокимычев",
      contactEmail: SITE_SUPPORT_EMAIL,
      contactPhone: "+79999226564",
      touristComment: "Прилетаем утренним рейсом.",
      organizerComments: [],
      statusHistory: [
        {
          id: "status-demo-new-1",
          from: null,
          to: "new",
          changedAt: now,
          changedBy: "system",
        },
      ],
      createdAt: now,
      updatedAt: now,
      fillTravelersLater: true,
      travelersFormToken: "trv-demo-new",
    },
    {
      id: "booking-demo-pending",
      userId: "ivan-evdokimychev",
      organizerTourId: "org-salta",
      tourId: "3",
      tourSlug: "salta-northwest",
      tourTitle: "Сальта и ХуХуй: горные деревни, виноградники и долина Калчакí",
      tourImage: tourCover("salta-northwest"),
      status: "pending",
      guests: 3,
      startDate: "2026-10-05",
      endDate: "2026-10-08",
      totalPriceUsd: 2100,
      contactName: "Иван Евдокимычев",
      contactEmail: SITE_SUPPORT_EMAIL,
      contactPhone: "+79999226564",
      organizerComments: [
        {
          id: "comment-demo-1",
          text: "Проверяем наличие мест на выбранные даты.",
          authorName: "Иван Евдокимычев",
          createdAt: now,
        },
      ],
      statusHistory: [
        {
          id: "status-demo-pending-1",
          from: null,
          to: "new",
          changedAt: "2026-06-01T10:24:00.000Z",
          changedBy: "system",
        },
        {
          id: "status-demo-pending-2",
          from: "new",
          to: "pending",
          changedAt: "2026-06-01T11:00:00.000Z",
          changedBy: "organizer",
        },
      ],
      createdAt: "2026-06-01T10:24:00.000Z",
      updatedAt: now,
      fillTravelersLater: true,
      travelersFormToken: "trv-demo-pending",
    },
    {
      id: "booking-demo-completed",
      userId: "ivan-evdokimychev",
      organizerTourId: "org-mendoza",
      tourId: "2",
      tourSlug: "mendoza-wine",
      tourTitle: "Мендоса: винные маршруты, Аконкагуа и гастрономические ужины",
      tourImage: tourCover("mendoza-wine"),
      status: "completed",
      guests: 2,
      startDate: "2025-11-03",
      endDate: "2025-11-05",
      totalPriceUsd: 1560,
      contactName: "Иван Евдокимычев",
      contactEmail: SITE_SUPPORT_EMAIL,
      contactPhone: "+79999226564",
      organizerComments: [
        {
          id: "comment-demo-2",
          text: "Места подтверждены. Отправили программу на email.",
          authorName: "Иван Евдокимычев",
          createdAt: "2025-10-05T12:10:00.000Z",
        },
      ],
      statusHistory: [
        {
          id: "status-demo-completed-1",
          from: null,
          to: "new",
          changedAt: "2025-10-01T10:00:00.000Z",
          changedBy: "system",
        },
        {
          id: "status-demo-completed-2",
          from: "new",
          to: "pending",
          changedAt: "2025-10-02T09:00:00.000Z",
          changedBy: "organizer",
        },
        {
          id: "status-demo-completed-3",
          from: "pending",
          to: "confirmed",
          changedAt: "2025-10-05T12:10:00.000Z",
          changedBy: "organizer",
        },
        {
          id: "status-demo-completed-4",
          from: "confirmed",
          to: "completed",
          changedAt: "2025-11-06T10:00:00.000Z",
          changedBy: "organizer",
        },
      ],
      createdAt: "2025-10-01T10:00:00.000Z",
      updatedAt: "2025-11-06T10:00:00.000Z",
      fillTravelersLater: false,
      travelersFormToken: "trv-demo-completed",
      travelersCompletedAt: "2025-10-08T14:30:00.000Z",
      travelers: [
        {
          id: "guest-1",
          fullName: "Иван Евдокимычев",
          dateOfBirth: "1990-05-15",
          passportNumber: "4510 123456",
          dietaryRestrictions: "Без ограничений",
          email: SITE_SUPPORT_EMAIL,
          phone: "+79999226564",
        },
        {
          id: "guest-2",
          fullName: "Мария Евдокимычева",
          dateOfBirth: "1992-08-22",
          passportNumber: "4511 654321",
          dietaryRestrictions: "Без глютена",
          email: "maria@example.com",
          phone: "+79991234567",
        },
      ],
    },
    {
      id: "booking-demo-tripster",
      userId: guestUserIdFromEmail("anna.k.demo@example.com"),
      organizerTourId: "org-iguazu",
      tourId: "4",
      tourSlug: "iguazu-falls",
      tourTitle: "Индивидуальный тур: водопады Игуасу (2 дня)",
      tourImage: tourCover("iguazu-falls"),
      status: "confirmed",
      guests: 2,
      startDate: "2026-09-12",
      endDate: "2026-09-13",
      totalPriceUsd: 890,
      contactName: "Анна и Михаил К.",
      contactEmail: "anna.k.demo@example.com",
      contactPhone: "+7 916 555-12-34",
      touristComment: "Бронирование с Tripster, нужен ранний выезд к парку.",
      organizerComments: [
        {
          id: "comment-tripster-1",
          text: "Билеты на аргентинскую сторону куплены. Ждём решение по бразильской.",
          authorName: "Иван Евдокимычев",
          createdAt: now,
        },
      ],
      statusHistory: [
        {
          id: "status-tripster-1",
          from: null,
          to: "new",
          changedAt: "2026-06-08T08:00:00.000Z",
          changedBy: "system",
          note: "Импорт с Tripster",
        },
        {
          id: "status-tripster-2",
          from: "new",
          to: "confirmed",
          changedAt: "2026-06-09T11:00:00.000Z",
          changedBy: "organizer",
        },
      ],
      createdAt: "2026-06-08T08:00:00.000Z",
      updatedAt: now,
      bookingSource: "tripster",
      externalReference: "TS-88421",
      clientPortalToken: "trip-demo-iguazu",
      travelersFormToken: "trv-demo-tripster",
      fillTravelersLater: true,
      tripOperations: buildTripsterIguazuDemoOperations(now),
    },
  ];
}
