import "server-only";

import { unstable_cache } from "next/cache";
import { fetchCutoverPublishedTourSlugs } from "@/lib/tours-server-cutover";
import {
  fetchPartnerTourSlugsResultServer,
} from "@/lib/tripster/partner-tour-server";
import {
  fetchYouTravelTourSlugsResultServer,
} from "@/lib/youtravel/partner-tour-server";
import { fetchExcursionSlugsServer } from "@/lib/excursion-server";
import { resolvePlacePage } from "@/lib/cms/place-resolver";
import { resolveBlogPost } from "@/lib/cms/blog-resolver";
import { resolveAuthorArticle } from "@/lib/cms/author-article-resolver";
import { getPlaceBySlug } from "@/data/places-seed";
import { getBlogPostBySlug } from "@/data/blog";
import { isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import {
  logPartnerSourceUnavailable,
  type PartnerSourceResult,
} from "@/lib/partner-source-result";

export type PublicDetailKind =
  | "tours"
  | "excursions"
  | "places"
  | "blog"
  | "author-articles";

export type ExistenceResult =
  | { status: "exists"; snapshotId: string }
  | { status: "missing"; reason: "confirmed_absent" | "retired" }
  | { status: "unavailable"; reason: string; retryable: true };

type SlugSourceSnapshot = {
  snapshotId: string;
  slugs: Set<string>;
  unavailableReasons: string[];
};

async function loadTourSlugSnapshot(): Promise<SlugSourceSnapshot> {
  const unavailableReasons: string[] = [];
  const slugs = new Set<string>();

  let native: string[] = [];
  try {
    native = await fetchCutoverPublishedTourSlugs();
    for (const slug of native) slugs.add(slug);
  } catch (error) {
    unavailableReasons.push(
      `platform:${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const [tripster, youtravel] = await Promise.all([
    fetchPartnerTourSlugsResultServer(),
    fetchYouTravelTourSlugsResultServer(),
  ]);

  if (tripster.status === "ok") {
    for (const slug of tripster.data) slugs.add(slug);
  } else {
    logPartnerSourceUnavailable("tripster_slugs", tripster);
    unavailableReasons.push(`tripster:${tripster.errorClass}`);
  }

  if (youtravel.status === "ok") {
    for (const slug of youtravel.data) slugs.add(slug);
  } else {
    logPartnerSourceUnavailable("youtravel_slugs", youtravel);
    unavailableReasons.push(`youtravel:${youtravel.errorClass}`);
  }

  const snapshotId = [
    `n${native.length}`,
    tripster.status === "ok" ? `t${tripster.data.length}` : "t-unavail",
    youtravel.status === "ok" ? `y${youtravel.data.length}` : "y-unavail",
  ].join(":");

  return { snapshotId, slugs, unavailableReasons };
}

const fetchPublicTourSlugSnapshot = unstable_cache(
  loadTourSlugSnapshot,
  ["public-tour-slug-snapshot-v3"],
  { revalidate: 300, tags: ["tours", "partner-tours", "youtravel-tours"] },
);

const fetchPublicExcursionSlugs = unstable_cache(
  fetchExcursionSlugsServer,
  ["public-excursion-slugs-v2"],
  { revalidate: 600, tags: ["excursions"] },
);

function asExistenceFromSlugList(
  slug: string,
  slugs: string[],
  snapshotId: string,
): ExistenceResult {
  if (slugs.includes(slug)) {
    return { status: "exists", snapshotId };
  }
  return { status: "missing", reason: "confirmed_absent" };
}

export async function resolvePublicDetailExistence(
  kind: PublicDetailKind,
  slug: string,
): Promise<ExistenceResult> {
  if (kind === "tours") {
    let snapshot: SlugSourceSnapshot;
    try {
      snapshot = await fetchPublicTourSlugSnapshot();
    } catch (error) {
      return {
        status: "unavailable",
        reason: error instanceof Error ? error.message : String(error),
        retryable: true,
      };
    }

    if (snapshot.slugs.has(slug)) {
      return { status: "exists", snapshotId: snapshot.snapshotId };
    }

    // Any partner/platform outage must not confirm absence.
    if (snapshot.unavailableReasons.length > 0) {
      return {
        status: "unavailable",
        reason: snapshot.unavailableReasons.join(","),
        retryable: true,
      };
    }

    return { status: "missing", reason: "confirmed_absent" };
  }

  if (kind === "excursions") {
    try {
      const slugs = await fetchPublicExcursionSlugs();
      return asExistenceFromSlugList(slug, slugs, `excursions:${slugs.length}`);
    } catch (error) {
      return {
        status: "unavailable",
        reason: error instanceof Error ? error.message : String(error),
        retryable: true,
      };
    }
  }

  if (kind === "places") {
    if (getPlaceBySlug(slug)) {
      return { status: "exists", snapshotId: "places-seed" };
    }
    try {
      const page = await resolvePlacePage(slug);
      return page
        ? { status: "exists", snapshotId: "places-cms" }
        : { status: "missing", reason: "confirmed_absent" };
    } catch (error) {
      return {
        status: "unavailable",
        reason: error instanceof Error ? error.message : String(error),
        retryable: true,
      };
    }
  }

  if (kind === "blog") {
    const filePost = getBlogPostBySlug(slug);
    if (filePost && !isAutoGeneratedBlogPost(filePost)) {
      return { status: "exists", snapshotId: "blog-seed" };
    }
    try {
      const post = await resolveBlogPost(slug);
      return post
        ? { status: "exists", snapshotId: "blog-cms" }
        : { status: "missing", reason: "confirmed_absent" };
    } catch (error) {
      return {
        status: "unavailable",
        reason: error instanceof Error ? error.message : String(error),
        retryable: true,
      };
    }
  }

  try {
    const article = await resolveAuthorArticle(slug);
    return article
      ? { status: "exists", snapshotId: "author-articles" }
      : { status: "missing", reason: "confirmed_absent" };
  } catch (error) {
    return {
      status: "unavailable",
      reason: error instanceof Error ? error.message : String(error),
      retryable: true,
    };
  }
}

/** @deprecated Prefer resolvePublicDetailExistence — boolean collapses unavailable → false. */
export async function publicDetailExists(
  kind: PublicDetailKind,
  slug: string,
): Promise<boolean> {
  const result = await resolvePublicDetailExistence(kind, slug);
  return result.status === "exists";
}

export type { PartnerSourceResult };
