import { beforeEach, describe, expect, it, vi } from "vitest";
import { CmsPublicContentUnavailableError } from "@/lib/cms/public-read-result";

const mocks = vi.hoisted(() => ({
  place: vi.fn(),
  blog: vi.fn(),
  author: vi.fn(),
}));

vi.mock("@/lib/cms/place-resolver", () => ({ resolvePlacePage: mocks.place }));
vi.mock("@/lib/cms/blog-resolver", () => ({ resolveBlogPost: mocks.blog }));
vi.mock("@/lib/cms/author-article-resolver", () => ({ resolveAuthorArticle: mocks.author }));
vi.mock("@/data/places-seed", () => ({ getPlaceBySlug: () => undefined }));
vi.mock("@/data/blog", () => ({ getBlogPostBySlug: () => undefined }));
vi.mock("@/lib/blog-utils", () => ({ isAutoGeneratedBlogPost: () => false }));
vi.mock("@/lib/tours-server-cutover", () => ({ fetchCutoverPublishedTourSlugs: async () => [] }));
vi.mock("@/lib/tripster/partner-tour-server", () => ({
  fetchPartnerTourSlugsResultServer: async () => ({ status: "ok", data: [] }),
}));
vi.mock("@/lib/youtravel/partner-tour-server", () => ({
  fetchYouTravelTourSlugsResultServer: async () => ({ status: "ok", data: [] }),
}));
vi.mock("@/lib/excursion-server", () => ({ fetchExcursionSlugsServer: async () => [] }));

import { resolvePublicDetailExistence } from "@/lib/public-detail-existence";

describe("CMS public detail existence", () => {
  beforeEach(() => {
    mocks.place.mockReset();
    mocks.blog.mockReset();
    mocks.author.mockReset();
  });

  it.each([
    ["places", mocks.place],
    ["blog", mocks.blog],
    ["author-articles", mocks.author],
  ] as const)("maps %s CMS outage to unavailable rather than missing", async (kind, resolver) => {
    resolver.mockRejectedValue(new CmsPublicContentUnavailableError("quota"));
    await expect(resolvePublicDetailExistence(kind, "cms-only")).resolves.toMatchObject({
      status: "unavailable",
      retryable: true,
    });
  });

  it("uses missing only after an available resolver confirms absence", async () => {
    mocks.place.mockResolvedValue(null);
    await expect(resolvePublicDetailExistence("places", "absent")).resolves.toEqual({
      status: "missing",
      reason: "confirmed_absent",
    });
  });
});
