import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("public detail status preflight", () => {
  it("checks dynamic detail slugs before a loading boundary can stream", () => {
    const middleware = readFileSync(join(process.cwd(), "src/middleware.ts"), "utf8");
    const route = readFileSync(
      join(
        process.cwd(),
        "src/app/api/public-detail-exists/[kind]/[slug]/route.ts",
      ),
      "utf8",
    );
    const routeMatcher = readFileSync(
      join(process.cwd(), "src/lib/public-detail-route.ts"),
      "utf8",
    );
    const existence = readFileSync(
      join(process.cwd(), "src/lib/public-detail-existence.ts"),
      "utf8",
    );

    expect(middleware).toContain("rejectMissingPublicDetail");
    expect(middleware).toContain("matchPublicDetailPath");
    expect(middleware).toContain("response.status !== 404");
    expect(middleware).toContain("signal: AbortSignal.timeout(1_500)");
    expect(routeMatcher).toContain('kind: "author-articles"');
    expect(routeMatcher).toContain("tours|excursions|places|blog");
    expect(route).toContain("status: exists ? 204 : 404");
    expect(route).toContain("status: 503");
    expect(route).toContain('"places"');
    expect(route).toContain('"author-articles"');
    expect(existence).toContain('kind === "places" && getPlaceBySlug(slug)');
    expect(existence).toContain("!isAutoGeneratedBlogPost(filePost)");
  });
});
