import "server-only";

import { unstable_cache } from "next/cache";
import { fetchCutoverPublishedTourSlugs } from "@/lib/tours-server-cutover";
import { fetchPartnerTourSlugsServer } from "@/lib/tripster/partner-tour-server";
import { fetchYouTravelTourSlugsServer } from "@/lib/youtravel/partner-tour-server";
import { fetchExcursionSlugsServer } from "@/lib/excursion-server";
import { resolvePlacePage } from "@/lib/cms/place-resolver";
import { resolveBlogPost } from "@/lib/cms/blog-resolver";
import { resolveAuthorArticle } from "@/lib/cms/author-article-resolver";
import { getPlaceBySlug } from "@/data/places-seed";
import { getBlogPostBySlug } from "@/data/blog";
import { isAutoGeneratedBlogPost } from "@/lib/blog-utils";

export type PublicDetailKind =
  | "tours"
  | "excursions"
  | "places"
  | "blog"
  | "author-articles";

const fetchPublicTourSlugs = unstable_cache(
  async () => {
    const [native, tripster, youtravel] = await Promise.all([
      fetchCutoverPublishedTourSlugs(),
      fetchPartnerTourSlugsServer().catch(() => [] as string[]),
      fetchYouTravelTourSlugsServer().catch(() => [] as string[]),
    ]);
    return [...new Set([...native, ...tripster, ...youtravel])];
  },
  ["public-tour-slugs-v2"],
  { revalidate: 600, tags: ["tours", "partner-tours", "youtravel-tours"] },
);

const fetchPublicExcursionSlugs = unstable_cache(
  fetchExcursionSlugsServer,
  ["public-excursion-slugs-v2"],
  { revalidate: 600, tags: ["excursions"] },
);

export async function publicDetailExists(
  kind: PublicDetailKind,
  slug: string,
): Promise<boolean> {
  if (kind === "tours") return (await fetchPublicTourSlugs()).includes(slug);
  if (kind === "excursions") return (await fetchPublicExcursionSlugs()).includes(slug);
  if (kind === "places" && getPlaceBySlug(slug)) return true;
  if (kind === "blog") {
    const filePost = getBlogPostBySlug(slug);
    if (filePost && !isAutoGeneratedBlogPost(filePost)) return true;
  }
  if (kind === "places") return Boolean(await resolvePlacePage(slug));
  if (kind === "blog") return Boolean(await resolveBlogPost(slug));
  return Boolean(await resolveAuthorArticle(slug));
}
