import type { EditorialRegistryEntry } from "@/editorial/types";

type EditorialRegistryInput = Omit<
  EditorialRegistryEntry,
  "allowedChildren" | "localizationSupport" | "densityDefault"
> &
  Partial<
    Pick<EditorialRegistryEntry, "allowedChildren" | "localizationSupport" | "densityDefault">
  >;

const base = (partial: EditorialRegistryInput): EditorialRegistryEntry => ({
  allowedChildren: [],
  localizationSupport: true,
  densityDefault: "comfortable",
  ...partial,
});

/** Single source of editorial block metadata for preview, CMS help, and audits. */
export const editorialBlockRegistry: Record<string, EditorialRegistryEntry> = {
  paragraph: base({
    type: "paragraph",
    label: "Текст",
    description: "Обычный абзац или безопасный HTML",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Семантический <p>; не схлопывать абзацы",
    seoBehaviour: "content",
    status: "stable",
    deprecatedAliases: ["text"],
  }),
  lead: base({
    type: "lead",
    label: "Лид",
    description: "Короткий вводный абзац статьи",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Один лид на статью по умолчанию",
    seoBehaviour: "content",
    status: "new",
  }),
  subheading: base({
    type: "subheading",
    label: "Подзаголовок",
    description: "H3 внутри раздела",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Иконка не входит в текст заголовка",
    seoBehaviour: "content",
    status: "stable",
    deprecatedAliases: ["heading"],
  }),
  callout: base({
    type: "callout",
    label: "Выноска",
    description: "Совет, предупреждение, обновление",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не полагаться только на цвет",
    seoBehaviour: "content",
    status: "stable",
    deprecatedAliases: ["infobox"],
    maxItems: 8,
  }),
  infobox: base({
    type: "infobox",
    label: "Инфобокс (legacy)",
    description: "Устаревший alias callout",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Мигрировать в callout",
    seoBehaviour: "content",
    status: "deprecated",
  }),
  media: base({
    type: "media",
    label: "Изображение",
    description: "Одно фото с подписью",
    group: "media",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "alt обязателен; caption ≠ alt",
    seoBehaviour: "content",
    status: "stable",
    deprecatedAliases: ["section-image"],
  }),
  photo: base({
    type: "photo",
    label: "Фотоблок",
    description: "Системный фотоблок с вариантами ширины и подписью",
    group: "media",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "next/image, без CLS, lazy по умолчанию",
    seoBehaviour: "content",
    status: "new",
  }),
  gallery: base({
    type: "gallery",
    label: "Галерея",
    description: "Сетка или карусель изображений",
    group: "media",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Клавиатура и подписи; не auto-play",
    seoBehaviour: "content",
    status: "stable",
    minItems: 2,
    maxItems: 12,
  }),
  "comparison-table": base({
    type: "comparison-table",
    label: "Сравнительная таблица",
    description: "Таблица с mobileLayout",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "cards",
    accessibilityNotes: "На mobile предпочитать cards/stacked",
    seoBehaviour: "content",
    status: "stable",
  }),
  table: base({
    type: "table",
    label: "Таблица",
    description: "Табличные данные",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "scroll",
    accessibilityNotes: "Заголовки th обязательны",
    seoBehaviour: "content",
    status: "stable",
  }),
  faq: base({
    type: "faq",
    label: "FAQ",
    description: "Вопросы и ответы в initial HTML",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "collapse",
    accessibilityNotes: "details/summary; JSON-LD только для видимых",
    seoBehaviour: "structured-data",
    status: "stable",
  }),
  accordion: base({
    type: "accordion",
    label: "Аккордеон",
    description: "Сворачиваемые блоки не-FAQ",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "collapse",
    accessibilityNotes: "Не удалять ответы из DOM",
    seoBehaviour: "content",
    status: "stable",
  }),
  checklist: base({
    type: "checklist",
    label: "Чек-лист",
    description: "Подготовка и контроль",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Интерактивность — opt-in",
    seoBehaviour: "content",
    status: "stable",
  }),
  steps: base({
    type: "steps",
    label: "Шаги",
    description: "Пошаговая инструкция",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Всегда вертикально на mobile",
    seoBehaviour: "content",
    status: "stable",
  }),
  map: base({
    type: "map",
    label: "Карта",
    description: "Одна точка",
    group: "travel",
    supportedThemes: "both",
    mobileBehaviour: "keep",
    accessibilityNotes: "Список локаций для screen reader",
    seoBehaviour: "content",
    status: "stable",
  }),
  "route-map": base({
    type: "route-map",
    label: "Маршрут",
    description: "Несколько точек",
    group: "travel",
    supportedThemes: "both",
    mobileBehaviour: "keep",
    accessibilityNotes: "List/map toggle на mobile",
    seoBehaviour: "content",
    status: "stable",
  }),
  cta: base({
    type: "cta",
    label: "CTA",
    description: "Основной призыв к действию",
    group: "commerce",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Максимум 1–2 CTA на статью",
    seoBehaviour: "ignore",
    status: "stable",
    maxItems: 2,
  }),
  "facts-grid": base({
    type: "facts-grid",
    label: "Факты",
    description: "Сетка ключевых фактов",
    group: "travel",
    supportedThemes: "both",
    mobileBehaviour: "cards",
    accessibilityNotes: "1–2 колонки на mobile",
    seoBehaviour: "content",
    status: "stable",
    maxItems: 8,
  }),
  "author-card": base({
    type: "author-card",
    label: "Автор",
    description: "Карточка автора или эксперта",
    group: "trust",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не подменять личный аватар редакционным",
    seoBehaviour: "structured-data",
    status: "stable",
  }),
  quote: base({
    type: "quote",
    label: "Цитата",
    description: "Редакционная или экспертная цитата",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "blockquote + cite",
    seoBehaviour: "content",
    status: "stable",
  }),
  video: base({
    type: "video",
    label: "Видео",
    description: "YouTube/Vimeo с lazy load",
    group: "media",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не грузить iframe до взаимодействия",
    seoBehaviour: "decorative",
    status: "stable",
  }),
  budget: base({
    type: "budget",
    label: "Бюджет",
    description: "Строки расходов с датой проверки",
    group: "travel",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не конвертировать валюты без источника",
    seoBehaviour: "content",
    status: "stable",
  }),
  seasons: base({
    type: "seasons",
    label: "Сезоны",
    description: "Плюсы и минусы по сезонам",
    group: "travel",
    supportedThemes: "both",
    mobileBehaviour: "cards",
    accessibilityNotes: "Источник и uncertainty",
    seoBehaviour: "content",
    status: "stable",
  }),
  "season-matrix": base({
    type: "season-matrix",
    label: "Матрица сезонов",
    description: "Виджет регионов × месяцев",
    group: "widgets",
    supportedThemes: "both",
    mobileBehaviour: "tabs",
    accessibilityNotes: "Селектор месяца на mobile",
    seoBehaviour: "content",
    status: "stable",
  }),
  "tourism-timeline": base({
    type: "tourism-timeline",
    label: "Таймлайн туризма",
    description: "Исторический/сезонный таймлайн",
    group: "widgets",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Вертикальный формат на mobile",
    seoBehaviour: "content",
    status: "stable",
  }),
  "tourism-infographic": base({
    type: "tourism-infographic",
    label: "Инфографика",
    description: "Туристическая инфографика",
    group: "widgets",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Текст не только в картинке",
    seoBehaviour: "content",
    status: "stable",
  }),
  widget: base({
    type: "widget",
    label: "Виджет",
    description: "Registry widget по ключу",
    group: "widgets",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Неизвестные ключи → fallback",
    seoBehaviour: "content",
    status: "stable",
  }),
  "article-summary": base({
    type: "article-summary",
    label: "Краткое содержание",
    description: "Карточки / deck ключевых моментов",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "cards",
    accessibilityNotes: "Без auto-play; клавиатура и reduced motion",
    seoBehaviour: "content",
    status: "new",
    minItems: 2,
    maxItems: 8,
  }),
  sources: base({
    type: "sources",
    label: "Источники",
    description: "Группы источников и дата проверки",
    group: "trust",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Ссылки остаются в HTML",
    seoBehaviour: "content",
    status: "new",
    minItems: 1,
  }),
  "country-tip": base({
    type: "country-tip",
    label: "Совет для русскоязычных",
    description: "Контекстный блок для русскоязычного читателя",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не вставлять автоматически в каждую статью",
    seoBehaviour: "content",
    status: "new",
  }),
  phrasebook: base({
    type: "phrasebook",
    label: "Разговорник",
    description: "Фразы original / translation / pronunciation",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Испанский текст не изображением; copy button",
    seoBehaviour: "content",
    status: "new",
    maxItems: 20,
  }),
  "option-selector": base({
    type: "option-selector",
    label: "Выбор варианта",
    description: "Селектор отрубов, регионов, документов",
    group: "widgets",
    supportedThemes: "both",
    mobileBehaviour: "tabs",
    accessibilityNotes: "Все варианты в initial HTML",
    seoBehaviour: "content",
    status: "new",
    minItems: 2,
    maxItems: 12,
  }),
  "pros-cons": base({
    type: "pros-cons",
    label: "Плюсы и минусы",
    description: "Сравнение за/против",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не полагаться только на цвет",
    seoBehaviour: "content",
    status: "new",
  }),
  bullets: base({
    type: "bullets",
    label: "Список",
    description: "Маркированный список",
    group: "content",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "ul/li",
    seoBehaviour: "content",
    status: "stable",
  }),
  divider: base({
    type: "divider",
    label: "Разделитель",
    description: "Горизонтальный разделитель",
    group: "layout",
    supportedThemes: "both",
    mobileBehaviour: "keep",
    accessibilityNotes: "decorative hr",
    seoBehaviour: "ignore",
    status: "stable",
  }),
  "ticket-link": base({
    type: "ticket-link",
    label: "Билеты",
    description: "Внешняя ссылка на билеты",
    group: "commerce",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Помечать внешние ссылки",
    seoBehaviour: "ignore",
    status: "stable",
  }),
  "tour-booking": base({
    type: "tour-booking",
    label: "Бронирование тура",
    description: "CTA на тур",
    group: "commerce",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Не дублировать с основным CTA",
    seoBehaviour: "ignore",
    status: "stable",
  }),
  "content-embed": base({
    type: "content-embed",
    label: "Вставка материала",
    description: "Тур, экскурсия, статья, гид",
    group: "commerce",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Релевантность обязательна",
    seoBehaviour: "content",
    status: "stable",
  }),
  "image-text": base({
    type: "image-text",
    label: "Фото и текст",
    description: "Split media/text",
    group: "media",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "На mobile — вертикальный стек",
    seoBehaviour: "content",
    status: "stable",
  }),
  "hero-banner": base({
    type: "hero-banner",
    label: "Hero-баннер",
    description: "Крупный вводный блок для страниц и хабов",
    group: "layout",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "Один hero на страницу; alt для фона",
    seoBehaviour: "content",
    status: "new",
  }),
  "related-links": base({
    type: "related-links",
    label: "Связанные материалы",
    description: "Список внутренних ссылок",
    group: "layout",
    supportedThemes: "both",
    mobileBehaviour: "stack",
    accessibilityNotes: "nav + список ссылок",
    seoBehaviour: "content",
    status: "new",
  }),
  "hub-cta-row": base({
    type: "hub-cta-row",
    label: "Ряд CTA хаба",
    description: "Карточки действий для хабов",
    group: "layout",
    supportedThemes: "both",
    mobileBehaviour: "cards",
    accessibilityNotes: "Не более 6 карточек; touch ≥ 44px",
    seoBehaviour: "ignore",
    status: "new",
    maxItems: 6,
  }),
};

export function getEditorialRegistryEntry(
  type: string,
): EditorialRegistryEntry | undefined {
  return editorialBlockRegistry[type];
}

export function listEditorialRegistryEntries(): EditorialRegistryEntry[] {
  return Object.values(editorialBlockRegistry);
}
