import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  PUBLIC_BOOKING_ERROR_MESSAGES,
  publicBookingError,
  resolvePublicBookingErrorMessage,
} from "@/lib/partner-booking/public-errors";

const root = process.cwd();

function source(relativePath: string): string {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

const routeFiles = [
  "src/app/api/excursions/[slug]/book/route.ts",
  "src/app/api/tripster/booking-request/route.ts",
  "src/app/api/youtravel/booking-request/route.ts",
] as const;

const bookingClientFiles = [
  "src/components/excursions/ExcursionBookingContactSection.tsx",
  "src/components/excursions/ExcursionBookingContext.tsx",
  "src/components/tour-detail/PartnerTourBookingContactSection.tsx",
] as const;

describe("release-visible booking and locale copy", () => {
  it("returns stable, traveler-safe Russian booking errors", () => {
    expect(publicBookingError("BOOKING_PRODUCT_NOT_FOUND")).toEqual({
      code: "BOOKING_PRODUCT_NOT_FOUND",
      error: PUBLIC_BOOKING_ERROR_MESSAGES.BOOKING_PRODUCT_NOT_FOUND,
    });
    expect(resolvePublicBookingErrorMessage("UNKNOWN_CODE")).toBe(
      PUBLIC_BOOKING_ERROR_MESSAGES.BOOKING_SERVICE_UNAVAILABLE,
    );

    for (const message of Object.values(PUBLIC_BOOKING_ERROR_MESSAGES)) {
      expect(message).toMatch(/[А-Яа-яЁё]/);
      expect(message).not.toMatch(
        /\b(?:api|server|supabase|provider|secret|token|key|env)\b|\.env|настро(?:ен|йк)/i,
      );
    }
  });

  it("uses public error codes in booking routes and never returns partner details", () => {
    for (const file of routeFiles) {
      const route = source(file);
      expect(route).toContain("publicBookingError(");
      expect(route).not.toMatch(/error:\s*contact\.error/);
      expect(route).not.toMatch(/return respond\([\s\S]{0,240}details:\s*error\.details/);
      expect(route).not.toMatch(/NextResponse\.json\(\{\s*error:\s*["']/);
    }

    expect(source("src/app/api/excursions/[slug]/book/route.ts")).toContain(
      "error.status >= 400 && error.status < 600 ? error.status : 400",
    );
    for (const file of [
      "src/app/api/tripster/booking-request/route.ts",
      "src/app/api/youtravel/booking-request/route.ts",
    ]) {
      expect(source(file)).toContain(
        "error.status >= 400 && error.status < 600 ? error.status : 502",
      );
    }
  });

  it("never renders raw booking response errors or partner field details", () => {
    for (const file of bookingClientFiles) {
      const client = source(file);
      expect(client).not.toContain("data.error");
      expect(client).not.toContain("data.details");
      expect(client).not.toContain("firstFieldError");
    }
  });

  it("keeps payment diagnostics and draft labels off public pages", () => {
    const payment = source("src/components/booking/BookingPaymentLinkView.tsx");
    expect(payment).not.toMatch(/плат[её]жн\w* провайдер|серверн\w* режим|ключ\w* плат[её]ж/i);
    expect(payment).not.toContain("error.message");
    expect(payment).not.toMatch(/не вернул checkout URL/i);

    const blogPage = source("src/app/blog/[slug]/page.tsx");
    const blogView = source("src/components/blog/BlogPostView.tsx");
    expect(blogPage).toContain("filterIndexableBlogPosts(blogPosts)");
    expect(blogPage).toContain("if (!post || isAutoGeneratedBlogPost(post))");
    expect(blogPage).toContain("notFound();");
    expect(blogView).not.toMatch(/черновик из контент-плана/i);

    const notifications = source("src/lib/notifications/booking-notifications.ts");
    expect(notifications).not.toMatch(/онлайн-оплата[^.]*скоро/i);
  });

  it("blocks technical setup and unfinished copy in public locale dictionaries", () => {
    for (const locale of ["en", "es", "pt"]) {
      const dictionary = source(`src/locales/${locale}/common.json`);
      expect(() => JSON.parse(dictionary)).not.toThrow();
      expect(dictionary).not.toMatch(
        /INTUI_API_KEY|AIRALO_FEED_(?:URL|PATH)|\.env(?:\.local)?|test exchange rates|tipos de prueba|taxas de teste|coming soon|готовится/i,
      );
    }
  });
});
