import { notFound } from "next/navigation";
import BlogPostView from "@/components/blog/BlogPostView";
import TranslationPreparingBanner from "@/components/i18n/TranslationPreparingBanner";
import ArticleJsonLd from "@/components/seo/ArticleJsonLd";
import BlogFaqJsonLd from "@/components/seo/BlogFaqJsonLd";
import { fetchMarketplaceTours } from "@/data/marketplace-tours-server";
import { blogPosts } from "@/data/blog";
import { getCmsResolverMetadata } from "@/lib/cms/content-resolver";
import { resolveBlogCatalog, resolveBlogPost } from "@/lib/cms/blog-resolver";
import { getCmsCutoverFlags } from "@/lib/cms/cms-cutover";
import { buildCmsContentHreflangAlternates } from "@/lib/cms/cms-hreflang";
import { getServerI18nLocale } from "@/lib/i18n/server-locale";
import { getBlogPostHeroResolved } from "@/lib/media-resolver";
import { buildPublicPageMetadata } from "@/lib/page-metadata";
import { isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import { absoluteUrl, resolvePublicUrl } from "@/lib/site-url";

interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  try {
    const catalog = await resolveBlogCatalog();
    return catalog.map((post) => ({ slug: post.slug }));
  } catch {
    const cutover = await getCmsCutoverFlags();
    return cutover.blog ? [] : blogPosts.map((post) => ({ slug: post.slug }));
  }
}

export async function generateMetadata({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const locale = await getServerI18nLocale();
  const post = await resolveBlogPost(slug, locale);
  if (!post) return { title: "Статья не найдена" };
  const alternates = await buildCmsContentHreflangAlternates("blog", slug);
  const canonicalPath = post.canonicalSlug ? `/blog/${post.canonicalSlug}` : `/blog/${slug}`;
  const pageMetadata = buildPublicPageMetadata({
    title: post.seoTitle ?? post.title,
    description: post.excerpt,
    path: `/blog/${slug}`,
    image: post.image,
  });
  return {
    ...pageMetadata,
    alternates: {
      ...alternates,
      ...pageMetadata.alternates,
      canonical: absoluteUrl(canonicalPath),
    },
    ...(isAutoGeneratedBlogPost(post)
      ? { robots: { index: false, follow: true } }
      : {}),
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const locale = await getServerI18nLocale();
  const post = await resolveBlogPost(slug, locale);

  if (!post) {
    notFound();
  }
  const cmsMetadata = getCmsResolverMetadata(post);

  const initialTours = await fetchMarketplaceTours();
  const heroSrc = resolvePublicUrl(getBlogPostHeroResolved(post).src);

  return (
    <>
      <link rel="preload" as="image" href={heroSrc} fetchPriority="high" />
      {cmsMetadata?.showTranslationBanner ? (
        <TranslationPreparingBanner locale={cmsMetadata.requestedLocale} />
      ) : null}
      {!isAutoGeneratedBlogPost(post) ? <ArticleJsonLd post={post} /> : null}
      {!isAutoGeneratedBlogPost(post) ? <BlogFaqJsonLd post={post} /> : null}
      <BlogPostView post={post} initialTours={initialTours} />
    </>
  );
}
