import { notFound, permanentRedirect } from "next/navigation";
import BlogPostView from "@/components/blog/BlogPostView";
import TranslationPreparingBanner from "@/components/i18n/TranslationPreparingBanner";
import ArticleJsonLd from "@/components/seo/ArticleJsonLd";
import BlogFaqJsonLd from "@/components/seo/BlogFaqJsonLd";
import { fetchMarketplaceTours } from "@/data/marketplace-tours-server";
import { blogPosts } from "@/data/blog";
import { cmsFallbackRobots, getCmsResolverMetadata } from "@/lib/cms/content-resolver";
import { resolveBlogCatalog, resolveBlogPost } from "@/lib/cms/blog-resolver";
import { areBlogSlugsEquivalent, blogPostPath } from "@/lib/blog-slug-resolve";
import { getCmsCutoverFlags } from "@/lib/cms/cms-cutover";
import { buildCmsContentHreflangAlternates } from "@/lib/cms/cms-hreflang";
import { getServerI18nLocale } from "@/lib/i18n/server-locale";
import { buildCmsPageMetadata } from "@/lib/cms/cms-page-metadata";
import { isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import { fetchSiteBlog, fetchSiteForms } from "@/lib/site-settings-server";
import { fetchContentExcursionsServer } from "@/lib/content-excursions-server";
import { resolveExcursionsForBlogPost } from "@/lib/content-excursion-match";

interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  try {
    const catalog = await resolveBlogCatalog();
    return catalog.map((post) => ({ slug: post.slug }));
  } catch {
    const cutover = await getCmsCutoverFlags();
    return cutover.blog ? [] : blogPosts.map((post) => ({ slug: post.slug }));
  }
}

export async function generateMetadata({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const locale = await getServerI18nLocale();
  const post = await resolveBlogPost(slug, locale);
  if (!post) return { title: "Статья не найдена" };
  const alternates = await buildCmsContentHreflangAlternates("blog", slug, locale);
  const canonicalPath = post.canonicalSlug ? `/blog/${post.canonicalSlug}` : `/blog/${slug}`;
  const pageMetadata = buildCmsPageMetadata({
    content: post,
    title: post.seoTitle ?? post.title,
    description: post.excerpt,
    path: `/blog/${slug}`,
    image: post.image,
    canonical: canonicalPath,
    alternates,
  });
  return {
    ...pageMetadata,
    ...((isAutoGeneratedBlogPost(post) || cmsFallbackRobots(post))
      ? { robots: { index: false, follow: true } }
      : {}),
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const locale = await getServerI18nLocale();
  const [catalog, post, blogSettings, forms, initialTours, contentExcursions] = await Promise.all([
    resolveBlogCatalog(locale),
    resolveBlogPost(slug, locale),
    fetchSiteBlog(),
    fetchSiteForms(),
    fetchMarketplaceTours(),
    fetchContentExcursionsServer(),
  ]);

  if (!post) {
    notFound();
  }

  if (!areBlogSlugsEquivalent(slug, post.slug)) {
    permanentRedirect(blogPostPath(post.slug));
  }

  const cmsMetadata = getCmsResolverMetadata(post);

  const excursionMatches = resolveExcursionsForBlogPost(post, contentExcursions);
  return (
    <>
      {cmsMetadata?.showTranslationBanner ? (
        <TranslationPreparingBanner locale={cmsMetadata.requestedLocale} />
      ) : null}
      {!isAutoGeneratedBlogPost(post) ? <ArticleJsonLd post={post} /> : null}
      {!isAutoGeneratedBlogPost(post) ? <BlogFaqJsonLd post={post} /> : null}
      <BlogPostView
        post={post}
        catalog={catalog}
        initialTours={initialTours}
        excursionMatches={excursionMatches}
        settings={blogSettings}
        newsletterEnabled={forms.newsletterEnabled}
      />
    </>
  );
}
