"use client";
import { RefreshCw, RotateCcw, XCircle } from "lucide-react";
import { AdminPageHeader, AdminPageShell } from "@/components/admin/AdminSidebar";
import CapabilityGate from "@/components/admin/CapabilityGate";
import IngestionTabs from "@/components/admin/ingestion/IngestionTabs";
import { Button } from "@/components/ui/button";
import { useAdminApi } from "@/hooks/useAdminApi";
import { cabinetTableWrapClass } from "@/lib/cabinet-ui";
import type { Json } from "@/types/database";
type Run = { id: string; status: string; trigger_kind: string; counts: Json; error_message: string | null; created_at: string; started_at: string | null; completed_at: string | null; ingestion_sources?: { name: string; source_type: string } | null };
const active = new Set(["pending", "fetching", "fetched", "normalizing", "processing", "publishing"]);
export default function IngestionRunsView() { const { data, loading, error, refresh } = useAdminApi<{ runs: Run[] }>("/api/admin/ingestion/runs"); async function act(id: string, action: "retry" | "cancel") { await fetch(`/api/admin/ingestion/runs/${id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); await refresh(); } return <CapabilityGate capability="ingestion_runs.view"><AdminPageShell><AdminPageHeader title="Запуски и очередь" subtitle="История обработки, ошибки и повторные попытки" actions={<Button variant="outline" size="sm" disabled={loading} onClick={() => void refresh()}><RefreshCw className="h-4 w-4" />Обновить</Button>} /><IngestionTabs />{error ? <p className="text-sm text-red-700">{error}</p> : null}<div className={cabinetTableWrapClass}><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-surface-muted"><tr><th className="p-3">Источник</th><th className="p-3">Запуск</th><th className="p-3">Состояние</th><th className="p-3">Результат</th><th className="p-3">Время</th><th className="p-3 text-right">Действия</th></tr></thead><tbody className="divide-y divide-border-subtle">{(data?.runs ?? []).map((run) => { const counts = run.counts && typeof run.counts === "object" && !Array.isArray(run.counts) ? run.counts : {}; return <tr key={run.id}><td className="p-3"><p className="font-medium">{run.ingestion_sources?.name ?? "Источник"}</p><p className="text-xs text-muted">{run.ingestion_sources?.source_type}</p></td><td className="p-3"><p>{run.trigger_kind === "manual" ? "Вручную" : run.trigger_kind}</p><p className="text-xs text-muted">{new Date(run.created_at).toLocaleString("ru-RU")}</p></td><td className="p-3"><span className="font-medium">{run.status}</span>{run.error_message ? <p className="mt-1 max-w-72 text-xs text-red-700">{run.error_message}</p> : null}</td><td className="p-3 text-xs text-muted">Получено: {String(counts.fetched ?? 0)} · На разбор: {String(counts.candidates ?? 0)} · Повторы: {String(counts.duplicates ?? 0)}</td><td className="p-3 text-muted">{run.started_at && run.completed_at ? `${Math.max(1, Math.round((new Date(run.completed_at).getTime() - new Date(run.started_at).getTime()) / 1000))} сек.` : active.has(run.status) ? "Выполняется" : "—"}</td><td className="p-3"><div className="flex justify-end gap-1">{active.has(run.status) ? <Button variant="ghost" size="icon" title="Остановить" onClick={() => void act(run.id, "cancel")}><XCircle className="h-4 w-4" /></Button> : null}{run.status === "failed" || run.status === "partial" ? <Button variant="outline" size="sm" onClick={() => void act(run.id, "retry")}><RotateCcw className="h-4 w-4" />Повторить</Button> : null}</div></td></tr>; })}{!loading && !(data?.runs.length) ? <tr><td colSpan={6} className="p-8 text-center text-muted">Запусков пока нет</td></tr> : null}</tbody></table></div></AdminPageShell></CapabilityGate>; }
