"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { AdminPageHeader, AdminPageShell } from "@/components/admin/AdminSidebar";
import CapabilityGate from "@/components/admin/CapabilityGate";
import IngestionTabs from "@/components/admin/ingestion/IngestionTabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAdminApi } from "@/hooks/useAdminApi";
import { cabinetCardClass } from "@/lib/cabinet-ui";
type Prompt = { id: string; task: string; version: number; model: string; system_prompt: string; status: string; activated_at: string | null };
export default function IngestionPromptsView() { const { data, error, refresh } = useAdminApi<{ prompts: Prompt[] }>("/api/admin/ingestion/prompts"); const [open, setOpen] = useState(false); const [task, setTask] = useState("content-analysis"); const [model, setModel] = useState("gpt-5.6-luna"); const [prompt, setPrompt] = useState(""); const [busy, setBusy] = useState(false); async function save() { setBusy(true); try { const response = await fetch("/api/admin/ingestion/prompts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ task, model, systemPrompt: prompt, activate: true }) }); if (!response.ok) throw new Error("Версия не сохранена"); setOpen(false); setPrompt(""); await refresh(); } finally { setBusy(false); } } return <CapabilityGate capability="prompts.view"><AdminPageShell><AdminPageHeader title="Правила анализа" subtitle="Версии редакционных инструкций и моделей" actions={<Button size="sm" onClick={() => setOpen((value) => !value)}><Plus className="h-4 w-4" />Новая версия</Button>} /><IngestionTabs />{error ? <p className="text-sm text-red-700">{error}</p> : null}{open ? <section className={`${cabinetCardClass} space-y-4 p-5`}><div className="grid gap-4 md:grid-cols-2"><label className="space-y-1 text-sm font-medium">Задача<Input value={task} onChange={(e) => setTask(e.target.value)} /></label><label className="space-y-1 text-sm font-medium">Модель<Input value={model} onChange={(e) => setModel(e.target.value)} /></label></div><label className="block space-y-1 text-sm font-medium">Инструкция<Textarea className="min-h-40" value={prompt} onChange={(e) => setPrompt(e.target.value)} /></label><Button disabled={busy || !prompt.trim()} onClick={() => void save()}>Сохранить и включить</Button></section> : null}<section className="space-y-3">{(data?.prompts ?? []).map((item) => <article key={item.id} className={`${cabinetCardClass} p-5`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{item.task} · версия {item.version}</h2><p className="mt-1 text-xs text-muted">{item.model}</p></div><span className={`rounded px-2 py-1 text-xs font-semibold ${item.status === "active" ? "bg-emerald-50 text-emerald-800" : "bg-surface-muted text-muted"}`}>{item.status === "active" ? "Действует" : item.status}</span></div><p className="mt-4 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-muted">{item.system_prompt}</p></article>)}</section></AdminPageShell></CapabilityGate>; }
