import Link from "next/link";
import { Clock, UserRound } from "lucide-react";
import BlogPostSectionView from "@/components/blog/BlogPostSectionView";
import BlogRelatedPosts from "@/components/blog/BlogRelatedPosts";
import BlogPostBreadcrumbs from "@/components/blog/BlogPostBreadcrumbs";
import BlogPostFooterLinks from "@/components/blog/BlogPostFooterLinks";
import BlogSidebar from "@/components/blog/BlogSidebar";
import BlogRichArticle from "@/components/blog/BlogRichArticle";
import BlogSectionBody from "@/components/blog/BlogSectionBody";
import BlogPostHero from "@/components/blog/BlogPostHero";
import ContentReadingLayout from "@/components/content/ContentReadingLayout";
import SharePageLinkButton from "@/components/content/SharePageLinkButton";
import BreadcrumbListJsonLd from "@/components/seo/BreadcrumbListJsonLd";
import { BLOG_EDITORIAL } from "@/data/blog-author";
import { getBlogRichArticle, getBlogRichArticleToc } from "@/data/blog-articles";
import {
  blogPosts,
  formatDate,
  formatBlogUpdatedLabel,
  sortBlogPostsByDate,
} from "@/data/blog";
import { resolveBlogCanonicalTarget } from "@/data/blog-canonical-map";
import { blogHubPath, getBlogHubFreshPosts, getPrimaryBlogHubForPost } from "@/data/blog-hubs";
import {
  buildBlogPostBreadcrumbJsonLd,
  buildBlogPostUiBreadcrumbs,
} from "@/lib/blog-breadcrumbs";
import {
  getBlogPostFooterLinks,
  getBlogPostSidebarRelatedResources,
} from "@/lib/blog-related-footer-links";
import { filterIndexableBlogPosts, isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import { getRelatedBlogPosts } from "@/lib/blog-related-posts";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/cn";
import { buildTocItemsFromHeadings, headingToAnchorId } from "@/lib/content-heading-id";
import { mapBlogRelatedResources } from "@/lib/content-related-links";
import { getRichArticleGallery } from "@/lib/media-resolver";
import { siteContainerClass } from "@/lib/site-container";
import TourEmbedSection from "@/components/embed/TourEmbedSection";
import type { BlogPost, TourListing } from "@/types";

type BlogPostViewProps = {
  post: BlogPost;
  initialTours?: TourListing[];
};

export default function BlogPostView({ post, initialTours = [] }: BlogPostViewProps) {
  const richArticle = post.richArticleId
    ? getBlogRichArticle(post.richArticleId)
    : undefined;

  const primaryHub = getPrimaryBlogHubForPost(post);
  const freshPosts = filterIndexableBlogPosts(
    sortBlogPostsByDate(blogPosts).filter((p) => p.slug !== post.slug),
  ).slice(0, 4);
  const hubFreshPosts = primaryHub
    ? getBlogHubFreshPosts(primaryHub, blogPosts, 4, post.slug)
    : undefined;

  const relatedPosts = isAutoGeneratedBlogPost(post)
    ? []
    : getRelatedBlogPosts(post, blogPosts);

  const uiBreadcrumbs = buildBlogPostUiBreadcrumbs(post);
  const sidebarRelatedResources = getBlogPostSidebarRelatedResources(post);
  const footerLinks = getBlogPostFooterLinks(post);

  const canonicalTarget = post.canonicalSlug
    ? {
        canonicalSlug: post.canonicalSlug,
        canonicalTitle:
          resolveBlogCanonicalTarget(post.slug)?.canonicalTitle ??
          blogPosts.find((p) => p.slug === post.canonicalSlug)?.title ??
          post.canonicalSlug,
      }
    : undefined;

  const usedIds = new Set<string>();
  const sectionsWithIds = (post.sections ?? []).map((section) => ({
    section,
    headingId: headingToAnchorId(section.title, usedIds),
  }));
  const tocItems = richArticle
    ? getBlogRichArticleToc(richArticle.id).map((item) => ({
        id: item.id,
        label: item.label,
        level: 2 as const,
      }))
    : buildTocItemsFromHeadings(
        sectionsWithIds.map(({ section }) => ({ heading: section.title }))
      );
  const sectionCount = post.sections?.length ?? 0;
  const showToc = sectionCount >= 8 || (richArticle?.sections.length ?? 0) >= 8;
  const effectiveTocItems = showToc ? tocItems : [];

  return (
    <>
      {!post.noIndex ? (
        <BreadcrumbListJsonLd items={buildBlogPostBreadcrumbJsonLd(post)} />
      ) : null}

      <section
        data-scroll-rail-tone="light"
        className="relative overflow-hidden border-b border-gray-100 bg-gradient-to-br from-surface-muted via-white to-sky/[0.06]"
      >
        <div className={cn(siteContainerClass, "relative py-8 md:py-10")}>
          <BlogPostBreadcrumbs items={uiBreadcrumbs} />

          <div className="mt-6 max-w-3xl">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div className="min-w-0 flex-1">
                  <span className="inline-flex rounded-full border border-sky/15 bg-sky/5 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-sky">
                    {post.category}
                  </span>
                  <h1 className="mt-4 font-display text-3xl font-bold leading-[1.12] tracking-tight text-charcoal sm:text-4xl lg:text-[2.5rem]">
                    {post.title}
                  </h1>
                  <div className="mt-4 max-w-2xl rounded-xl border border-gray-200/80 bg-white/70 px-4 py-3.5 shadow-sm backdrop-blur-sm sm:px-5 sm:py-4">
                    <p className="text-base leading-[1.7] text-slate sm:text-lg">{post.excerpt}</p>
                  </div>
                </div>
                <SharePageLinkButton title={post.title} className="shrink-0" />
              </div>

              <div className="mt-5 flex flex-wrap items-center gap-3 text-sm text-slate">
                <span className="inline-flex items-center gap-1.5">
                  <UserRound className="h-4 w-4 text-sky/70" aria-hidden />
                  {post.author}
                </span>
                <span aria-hidden>·</span>
                <span>{formatDate(post.date)}</span>
                <span aria-hidden>·</span>
                <span className="inline-flex items-center gap-1">
                  <Clock className="h-4 w-4" aria-hidden />
                  {post.readTime}
                </span>
                {!post.noIndex ? (
                  <>
                    <span aria-hidden>·</span>
                    <span>{formatBlogUpdatedLabel(post)}</span>
                  </>
                ) : null}
              </div>

              <ul className="mt-4 flex flex-wrap gap-2">
                {post.tags.map((tag) => (
                  <li
                    key={tag}
                    className="rounded-full border border-gray-200 bg-white px-3 py-1 text-xs font-medium text-slate"
                  >
                    #{tag}
                  </li>
                ))}
              </ul>
          </div>
        </div>
      </section>

      <BlogPostHero post={post} />

      <div className="bg-surface-muted pb-16">
        <div className={cn(siteContainerClass, "py-8 md:py-10")}>
          <ContentReadingLayout
            tocItems={effectiveTocItems}
            tocMinItems={8}
            aside={
              <BlogSidebar
                freshPosts={freshPosts}
                hubFreshPosts={hubFreshPosts}
                hubLabel={primaryHub?.shortTitle}
                hubHref={primaryHub ? blogHubPath(primaryHub.id) : undefined}
                defaultHubScope={Boolean(hubFreshPosts?.length)}
                embedded
              />
            }
            relatedItems={
              sidebarRelatedResources.length
                ? mapBlogRelatedResources(sidebarRelatedResources)
                : []
            }
            relatedTitle="Читайте также"
            articleClassName="content-reading-prose--wide"
            footer={
              <footer>
                <div className="flex flex-wrap items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-sky/10 text-sm font-bold text-sky">
                    {post.author.charAt(0)}
                  </div>
                  <div>
                    <p className="font-medium text-charcoal">{post.author}</p>
                    <p className="text-sm text-slate">{post.authorBio ?? BLOG_EDITORIAL.bio}</p>
                  </div>
                </div>
                <BlogPostFooterLinks links={footerLinks} />
              </footer>
            }
          >
            <div className="space-y-4">
              {canonicalTarget ? (
                <aside className="rounded-2xl border border-amber-200/80 bg-amber-50/90 p-4 text-sm leading-relaxed text-amber-950">
                  <p className="font-medium">Это черновик из контент-плана.</p>
                  <p className="mt-1">
                    Актуальный материал по теме —{" "}
                    <Link
                      href={`/blog/${canonicalTarget.canonicalSlug}`}
                      className="font-semibold text-sky hover:underline"
                    >
                      {canonicalTarget.canonicalTitle}
                    </Link>
                    .
                  </p>
                </aside>
              ) : null}
              {richArticle ? (
                <BlogRichArticle
                  article={richArticle}
                  galleryImages={
                    post.richArticleId ? getRichArticleGallery(post.richArticleId) : undefined
                  }
                />
              ) : post.sections?.length ? (
                <div className="space-y-10">
                  {sectionsWithIds.map(({ section, headingId }, index) => (
                    <BlogPostSectionView
                      key={section.title}
                      section={section}
                      headingId={headingId}
                      index={index}
                      postSlug={post.slug}
                      totalSections={sectionsWithIds.length}
                    />
                  ))}
                </div>
              ) : post.content ? (
                <BlogSectionBody section={{ title: "", body: post.content }} postSlug={post.slug} />
              ) : null}
            </div>

            {post.tourEmbeds?.length && initialTours.length > 0 ? (
              <div className="mt-10 space-y-8 border-t border-gray-100 pt-8">
                {post.tourEmbeds.map((embed) => (
                  <TourEmbedSection
                    key={embed.id ?? `${embed.variant}-${embed.title}`}
                    config={{ ...embed, tone: embed.tone ?? "inline" }}
                    initialTours={initialTours}
                  />
                ))}
              </div>
            ) : null}
          </ContentReadingLayout>

          {!post.noIndex && relatedPosts.length > 0 ? (
            <BlogRelatedPosts posts={relatedPosts} className="mt-10" />
          ) : null}

          <div className="mt-8 rounded-3xl border border-sky/15 bg-gradient-to-br from-sky/[0.06] to-white p-6 text-center shadow-card sm:p-8">
            <p className="font-heading text-xl font-bold text-charcoal">Планируете поездку?</p>
            <p className="mt-2 text-sm text-slate">
              {post.tourEmbeds?.length
                ? "Дополните маршрут материалами путеводителя или напишите нам"
                : "Соберите маршрут в путеводителе или выберите готовый тур с гидом"}
            </p>
            <div className="mt-5 flex flex-wrap justify-center gap-3">
              <Link href="/guide" className={cn(buttonVariants(), "rounded-full px-6")}>
                Путеводитель
              </Link>
              {!post.tourEmbeds?.length ? (
                <Link href="/tours" className={cn(buttonVariants({ variant: "outline" }), "rounded-full px-6")}>
                  Каталог туров
                </Link>
              ) : null}
              <Link href="/contacts" className={cn(buttonVariants({ variant: "ghost" }), "rounded-full px-6")}>
                Контакты
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
