"use client";

import Link from "next/link";
import { Clock, UserRound } from "lucide-react";
import { BlogCardAuthorOverlay } from "@/components/blog/BlogCardAuthorOverlay";
import { SafeImage } from "@/components/ui/safe-image";
import type { BlogPost, BlogCardVariant } from "@/types";
import { formatDate, formatBlogUpdatedLabel } from "@/data/blog";
import { isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import { cn } from "@/lib/cn";
import {
  ContentCard,
  ContentCardBody,
  ContentCardMedia,
  ContentCardOverlayLink,
  ContentCardTitle,
  contentCardMediaHoverClass,
} from "@/components/content/ContentCard";

type BlogCardProps = {
  post: BlogPost;
  variant?: BlogCardVariant;
  priority?: boolean;
};

function MetaRow({ post, className, showAuthor = false }: { post: BlogPost; className?: string; showAuthor?: boolean }) {
  const isDraft = isAutoGeneratedBlogPost(post);

  return (
    <div className={cn("flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-slate", className)}>
      {showAuthor ? (
        <>
          <span className="inline-flex min-w-0 max-w-full items-center gap-1 font-medium text-charcoal/75">
            <UserRound className="h-3 w-3 shrink-0 text-sky/70" aria-hidden />
            <span className="truncate">{post.author}</span>
          </span>
          <span aria-hidden>·</span>
        </>
      ) : null}
      <span>{formatDate(post.date)}</span>
      <span aria-hidden>·</span>
      <span className="inline-flex items-center gap-1">
        <Clock className="h-3 w-3" aria-hidden />
        {post.readTime}
      </span>
      {!isDraft ? (
        <>
          <span aria-hidden>·</span>
          <span>{formatBlogUpdatedLabel(post)}</span>
        </>
      ) : null}
    </div>
  );
}

function TagList({ tags, limit = 3 }: { tags: string[]; limit?: number }) {
  const visible = tags.slice(0, limit);
  return (
    <ul className="flex flex-wrap gap-1.5">
      {visible.map((tag) => (
        <li key={tag}>
          <Link
            href={`/blog?tag=${encodeURIComponent(tag)}`}
            className="rounded-full border border-border-subtle bg-surface-elevated/80 px-2 py-0.5 text-2xs font-medium uppercase tracking-wide text-slate transition-colors hover:border-sky/30 hover:text-sky"
          >
            {tag}
          </Link>
        </li>
      ))}
    </ul>
  );
}

function CardBadges({ post }: { post: BlogPost }) {
  const isDraft = isAutoGeneratedBlogPost(post);

  return (
    <div className="pointer-events-none absolute inset-x-3 top-3 z-10 flex flex-wrap items-start justify-between gap-2">
      <span className="max-w-[55%] rounded-full border border-white/30 bg-white/90 px-3 py-1 text-xs font-semibold text-charcoal backdrop-blur-sm sm:max-w-none">
        {post.category}
      </span>
      <div className="flex max-w-[45%] flex-col items-end gap-1.5 sm:max-w-none sm:flex-row sm:flex-wrap sm:justify-end">
        {post.richArticleId ? (
          <span className="rounded-full bg-sky px-2.5 py-1 text-2xs font-semibold uppercase tracking-wide text-white backdrop-blur-sm sm:text-xs">
            Полный гид
          </span>
        ) : isDraft ? (
          <span className="rounded-full bg-slate/80 px-2.5 py-1 text-2xs font-semibold uppercase tracking-wide text-white backdrop-blur-sm sm:text-xs">
            Черновик
          </span>
        ) : null}
      </div>
    </div>
  );
}

function FeaturedBadges({ post }: { post: BlogPost }) {
  return (
    <div className="pointer-events-none absolute inset-x-4 top-4 z-10 flex flex-wrap items-start justify-between gap-2">
      <span className="rounded-full border border-sky/20 bg-sky/90 px-3 py-1 text-xs font-semibold text-white backdrop-blur-sm">
        {post.category}
      </span>
      <div className="flex flex-col items-end gap-1.5 sm:flex-row sm:flex-wrap sm:justify-end">
        {post.richArticleId ? (
          <span className="rounded-full bg-sky px-3 py-1 text-xs font-semibold text-white backdrop-blur-sm">
            Полный гид
          </span>
        ) : null}
      </div>
    </div>
  );
}

export default function BlogCard({ post, variant = post.cardVariant ?? "standard", priority }: BlogCardProps) {
  const isDraft = isAutoGeneratedBlogPost(post);
  const imagePriority = priority === true;
  const imageLoading = imagePriority ? undefined : ("lazy" as const);

  if (variant === "featured") {
    return (
      <article className="group relative col-span-full grid overflow-hidden rounded-panel border border-border-subtle bg-surface-elevated shadow-card transition-shadow hover:shadow-elevated motion-reduce:transition-none md:grid-cols-[1.15fr_1fr]">
        <Link
          href={`/blog/${post.slug}`}
          className="absolute inset-0 z-0 rounded-panel focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky/40 focus-visible:ring-offset-2"
          aria-label={post.title}
        />
        <div className="relative aspect-[16/10] min-h-[220px] md:min-h-[320px] md:aspect-auto">
          <SafeImage
            src={post.image}
            alt={post.title}
            fill
            className="object-cover transition-transform duration-500 group-hover:scale-[1.03] motion-reduce:transform-none"
            sizes="(max-width: 768px) 100vw, 60vw"
            priority={imagePriority}
            loading={imageLoading}
            placeholderVariant="destination"
          />
          <FeaturedBadges post={post} />
          <BlogCardAuthorOverlay post={post} featured />
          <div
            className="pointer-events-none absolute inset-0 z-[1] bg-gradient-to-t from-charcoal/35 via-charcoal/5 to-transparent transition-opacity duration-300 group-hover:opacity-0 motion-reduce:transition-none"
            aria-hidden
          />
        </div>
        <div className="pointer-events-none relative flex flex-col justify-center p-6 sm:p-8">
          <MetaRow post={post} showAuthor />
          <h2 className="mt-3 font-heading text-2xl font-bold leading-snug text-charcoal transition-colors group-hover:text-sky sm:text-3xl">
            {post.title}
          </h2>
          <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-slate sm:text-base">{post.excerpt}</p>
          <div className="pointer-events-auto relative z-10 mt-4">
            <TagList tags={post.tags} limit={4} />
          </div>
        </div>
      </article>
    );
  }

  if (variant === "compact") {
    return (
      <Link
        href={`/blog/${post.slug}`}
        className="group flex min-h-[44px] gap-3 rounded-card border border-transparent p-2 transition-colors hover:border-border-subtle hover:bg-surface-elevated focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky/40 focus-visible:ring-offset-2"
      >
        <div className="relative h-[4.5rem] w-[4.5rem] shrink-0 overflow-hidden rounded-xl bg-surface-muted ring-1 ring-border-subtle/60">
          <SafeImage
            src={post.image}
            alt={post.title}
            fill
            className="object-cover"
            sizes="72px"
            loading="lazy"
            placeholderVariant="destination"
            placeholderCompact
          />
        </div>
        <div className="min-w-0 flex-1">
          <p className="line-clamp-2 text-sm font-medium leading-snug text-charcoal group-hover:text-sky">
            {post.title}
          </p>
          <p className="mt-1 text-xs text-slate">
            {post.readTime}
            {!isDraft ? ` · ${formatBlogUpdatedLabel(post)}` : isDraft ? " · Черновик" : ""}
          </p>
        </div>
      </Link>
    );
  }

  return (
    <ContentCard radius="panel" className="h-full ring-1 ring-charcoal/[0.04]">
      <ContentCardOverlayLink href={`/blog/${post.slug}`} ariaLabel={post.title} radius="panel" />
      <ContentCardMedia aspect="3/2" gradient="none">
        <SafeImage
          src={post.image}
          alt={post.title}
          fill
          className={contentCardMediaHoverClass}
          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
          priority={imagePriority}
          loading={imageLoading}
          placeholderVariant="destination"
        />
        <CardBadges post={post} />
        <BlogCardAuthorOverlay post={post} />
        <div
          className="pointer-events-none absolute inset-0 z-[1] bg-gradient-to-t from-charcoal/30 via-transparent to-transparent transition-opacity duration-300 group-hover:opacity-0 motion-reduce:transition-none"
          aria-hidden
        />
      </ContentCardMedia>
      <ContentCardBody padding="blog">
        <MetaRow post={post} showAuthor />
        <ContentCardTitle>{post.title}</ContentCardTitle>
        <p className="mt-2 line-clamp-3 flex-1 text-sm leading-relaxed text-slate">{post.excerpt}</p>
        <div className="pointer-events-auto relative z-10 mt-4 border-t border-border-subtle/60 pt-4">
          <TagList tags={post.tags} />
        </div>
      </ContentCardBody>
    </ContentCard>
  );
}
