import Link from "next/link";
import BlogPostSectionView from "@/components/blog/BlogPostSectionView";
import BlogRelatedPosts from "@/components/blog/BlogRelatedPosts";
import BlogPostFooterLinks from "@/components/blog/BlogPostFooterLinks";
import BlogSidebar from "@/components/blog/BlogSidebar";
import BlogPostHeader from "@/components/blog/BlogPostHeader";
import BlogPostNav from "@/components/blog/BlogPostNav";
import BlogAuthorCard from "@/components/blog/BlogAuthorCard";
import BlogQuickFacts from "@/components/blog/BlogQuickFacts";
import BlogShareBar from "@/components/blog/BlogShareBar";
import BlogNewsletterBlock from "@/components/blog/BlogNewsletterBlock";
import BlogArticleFeedback from "@/components/blog/BlogArticleFeedback";
import BlogCommentsSection from "@/components/blog/BlogCommentsSection";
import BlogEngagementCta from "@/components/blog/BlogEngagementCta";
import BlogAffiliateZone from "@/components/blog/BlogAffiliateZone";
import BlogDestinationGallery from "@/components/blog/BlogDestinationGallery";
import BlogTopicClusterNav from "@/components/blog/BlogTopicClusterNav";
import BlogTopicClusterJsonLd from "@/components/blog/BlogTopicClusterJsonLd";
import BlogReadingHistoryRecorder from "@/components/blog/BlogReadingHistoryRecorder";
import ArticlePlacesMiniMap from "@/components/blog/ArticlePlacesMiniMap";
import BlogRichArticle from "@/components/blog/BlogRichArticle";
import BlogSectionBody from "@/components/blog/BlogSectionBody";
import ContentReadingLayout from "@/components/content/ContentReadingLayout";
import ArticleReadingProgress from "@/components/content/ArticleReadingProgress";
import CollapsibleAsidePanel from "@/components/content/CollapsibleAsidePanel";
import BreadcrumbListJsonLd from "@/components/seo/BreadcrumbListJsonLd";
import { getBlogRichArticle, getBlogRichArticleToc } from "@/data/blog-articles";
import {
  blogPosts,
  sortBlogPostsByDate,
} from "@/data/blog";
import { resolveBlogCanonicalTarget } from "@/data/blog-canonical-map";
import { blogHubPath, getBlogHubFreshPosts, getPrimaryBlogHubForPost } from "@/data/blog-hubs";
import {
  buildBlogPostBreadcrumbJsonLd,
  buildBlogPostUiBreadcrumbs,
} from "@/lib/blog-breadcrumbs";
import { getBlogAdjacentPosts } from "@/lib/blog-adjacent-posts";
import {
  getBlogPostFooterLinks,
  getBlogPostSidebarRelatedResources,
} from "@/lib/blog-related-footer-links";
import { filterIndexableBlogPosts, isAutoGeneratedBlogPost } from "@/lib/blog-utils";
import { getRelatedBlogPosts, getRelatedBlogPostsForSection } from "@/lib/blog-related-posts";
import { buildInlineRelatedPostsBySection } from "@/lib/blog-inline-related";
import { buildInlineRelatedForRichArticle } from "@/lib/blog-inline-related-rich";
import { resolveBlogPostDestinations } from "@/lib/blog-destinations";
import { buildPublishedBlogSlugSet } from "@/lib/blog-slug-resolve";
import { extractArticleMapPoints, extractSectionMapPoints } from "@/lib/article-map-points";
import { cn } from "@/lib/cn";
import { getBlogSectionKind } from "@/lib/blog-section-body";
import { buildTocItemsFromHeadings, headingToAnchorId } from "@/lib/content-heading-id";
import { mapBlogRelatedResources } from "@/lib/content-related-links";
import { getRichArticleGallery } from "@/lib/media-resolver";
import { siteContainerClass } from "@/lib/site-container";
import TourEmbedSection from "@/components/embed/TourEmbedSection";
import type { BlogPost, TourListing } from "@/types";

type BlogPostViewProps = {
  post: BlogPost;
  /** Published catalog; defaults to TS seed for admin preview routes. */
  catalog?: BlogPost[];
  initialTours?: TourListing[];
};

const TOC_MIN_SECTIONS = 4;

export default function BlogPostView({
  post,
  catalog = filterIndexableBlogPosts(blogPosts),
  initialTours = [],
}: BlogPostViewProps) {
  const publishedBlogSlugs = buildPublishedBlogSlugSet(catalog.map((entry) => entry.slug));
  const richArticle = post.richArticleId
    ? getBlogRichArticle(post.richArticleId)
    : undefined;

  const primaryHub = getPrimaryBlogHubForPost(post);
  const freshPosts = filterIndexableBlogPosts(
    sortBlogPostsByDate(catalog).filter((p) => p.slug !== post.slug),
  ).slice(0, 4);
  const hubFreshPosts = primaryHub
    ? getBlogHubFreshPosts(primaryHub, catalog, 4, post.slug)
    : undefined;

  const relatedPosts = isAutoGeneratedBlogPost(post)
    ? []
    : getRelatedBlogPosts(post, catalog);

  const adjacentPosts = getBlogAdjacentPosts(post, catalog);
  const uiBreadcrumbs = buildBlogPostUiBreadcrumbs(post);
  const sidebarRelatedResources = getBlogPostSidebarRelatedResources(
    post,
    publishedBlogSlugs,
  );
  const footerLinks = getBlogPostFooterLinks(post, publishedBlogSlugs);

  const canonicalTarget = post.canonicalSlug
    ? {
        canonicalSlug: post.canonicalSlug,
        canonicalTitle:
          resolveBlogCanonicalTarget(post.slug)?.canonicalTitle ??
          catalog.find((p) => p.slug === post.canonicalSlug)?.title ??
          post.canonicalSlug,
      }
    : undefined;

  const usedIds = new Set<string>();
  const sectionsWithIds = (post.sections ?? []).map((section) => ({
    section,
    headingId: headingToAnchorId(section.title, usedIds),
  }));
  const tocItems = richArticle
    ? getBlogRichArticleToc(richArticle.id).map((item) => ({
        id: item.id,
        label: item.label,
        level: 2 as const,
      }))
    : buildTocItemsFromHeadings(
        sectionsWithIds.map(({ section }) => ({ heading: section.title }))
      );
  const sectionCount = richArticle?.sections.length ?? post.sections?.length ?? 0;
  const showToc = sectionCount >= TOC_MIN_SECTIONS;
  const effectiveTocItems = showToc ? tocItems : [];
  const articleMapPoints = extractArticleMapPoints(post);
  const postDestinations = !post.noIndex ? resolveBlogPostDestinations(post) : [];
  const inlineRelatedBySection =
    !post.noIndex && !richArticle && post.sections?.length
      ? buildInlineRelatedPostsBySection(post, catalog, post.sections, ({ section }, excludeSlugs) =>
          getRelatedBlogPostsForSection(
            post,
            catalog,
            {
              sectionTitle: section.title,
              sectionBody: section.body,
              sectionKind: getBlogSectionKind(section.title, section.blockType),
            },
            excludeSlugs,
            2,
          ),
        )
      : new Map<number, BlogPost[]>();

  const inlineRelatedRichBySection =
    !post.noIndex && richArticle
      ? buildInlineRelatedForRichArticle(post, catalog, richArticle, (context, excludeSlugs) =>
          getRelatedBlogPostsForSection(
            post,
            catalog,
            {
              sectionTitle: context.sectionTitle,
              sectionBody: context.sectionBody,
            },
            excludeSlugs,
            2,
          ),
        )
      : new Map<number, BlogPost[]>();

  return (
    <>
      {!post.noIndex ? <BlogReadingHistoryRecorder post={post} /> : null}
      {!post.noIndex ? <BlogTopicClusterJsonLd post={post} catalog={catalog} /> : null}
      {!post.noIndex ? <ArticleReadingProgress /> : null}

      {!post.noIndex ? (
        <BreadcrumbListJsonLd items={buildBlogPostBreadcrumbJsonLd(post)} />
      ) : null}

      <BlogPostHeader post={post} breadcrumbs={uiBreadcrumbs} />

      <div className="bg-surface-muted pb-16">
        <div className={cn(siteContainerClass, "py-8 md:py-10")}>
          <ContentReadingLayout
            tocItems={effectiveTocItems}
            tocMinItems={TOC_MIN_SECTIONS}
            collapsiblePanels={false}
            relatedOutsideArticle
            aside={
              <div className="space-y-4">
                {articleMapPoints.length > 0 ? (
                  <CollapsibleAsidePanel
                    title="На карте"
                    storageKey="blog-map-collapsed"
                    collapsedHint={`${articleMapPoints.length} точек`}
                  >
                    <ArticlePlacesMiniMap points={articleMapPoints} />
                  </CollapsibleAsidePanel>
                ) : null}
                <BlogSidebar
                  freshPosts={freshPosts}
                  hubFreshPosts={hubFreshPosts}
                  hubLabel={primaryHub?.shortTitle}
                  hubHref={primaryHub ? blogHubPath(primaryHub.id) : undefined}
                  defaultHubScope={Boolean(hubFreshPosts?.length)}
                  readingHistoryExcludeSlug={post.slug}
                />
              </div>
            }
            relatedItems={
              sidebarRelatedResources.length
                ? mapBlogRelatedResources(sidebarRelatedResources)
                : []
            }
            relatedTitle="Читайте также"
            articleClassName="content-reading-prose--wide"
            footer={
              <footer className="space-y-8">
                <BlogShareBar post={post} />
                {!post.noIndex ? (
                  <BlogArticleFeedback slug={post.slug} title={post.title} />
                ) : null}
                {!post.noIndex ? (
                  <BlogCommentsSection slug={post.slug} title={post.title} />
                ) : null}
                <BlogAuthorCard post={post} />
                <BlogPostFooterLinks links={footerLinks} />
                {!post.noIndex ? (
                  <BlogNewsletterBlock source={`blog:${post.slug}`} />
                ) : null}
              </footer>
            }
          >
            {!post.noIndex ? <BlogQuickFacts post={post} className="mb-8" /> : null}
            {!post.noIndex && postDestinations.length > 0 ? (
              <BlogDestinationGallery destinations={postDestinations} className="mb-8" />
            ) : null}
            {!post.noIndex ? (
              <BlogTopicClusterNav post={post} catalog={catalog} className="mb-8" />
            ) : null}
            <div className="space-y-4">
              {canonicalTarget ? (
                <aside className="rounded-2xl border border-amber-200/80 bg-amber-50/90 p-4 text-sm leading-relaxed text-amber-950">
                  <p className="font-medium">Это черновик из контент-плана.</p>
                  <p className="mt-1">
                    Актуальный материал по теме —{" "}
                    <Link
                      href={`/blog/${canonicalTarget.canonicalSlug}`}
                      className="font-semibold text-sky hover:underline"
                    >
                      {canonicalTarget.canonicalTitle}
                    </Link>
                    .
                  </p>
                </aside>
              ) : null}
              {richArticle ? (
                <BlogRichArticle
                  article={richArticle}
                  galleryImages={
                    post.richArticleId ? getRichArticleGallery(post.richArticleId) : undefined
                  }
                  inlineRelatedBySection={inlineRelatedRichBySection}
                  sourceSlug={post.slug}
                />
              ) : post.sections?.length ? (
                <div className="space-y-10">
                  {sectionsWithIds.map(({ section, headingId }, index) => (
                    <BlogPostSectionView
                      key={section.title}
                      section={section}
                      headingId={headingId}
                      index={index}
                      postSlug={post.slug}
                      totalSections={sectionsWithIds.length}
                      inlineRelatedPosts={inlineRelatedBySection.get(index)}
                      sectionMapPoints={extractSectionMapPoints(section)}
                    />
                  ))}
                </div>
              ) : post.content ? (
                <BlogSectionBody
                  section={{ title: "", body: post.content }}
                  postSlug={post.slug}
                  linkifyText
                />
              ) : null}
            </div>

            {!post.noIndex ? <BlogAffiliateZone post={post} className="mt-10" /> : null}

            {post.tourEmbeds?.length && initialTours.length > 0 ? (
              <div className="mt-10 space-y-8 border-t border-gray-100 pt-8">
                {post.tourEmbeds.map((embed) => (
                  <TourEmbedSection
                    key={embed.id ?? `${embed.variant}-${embed.title}`}
                    config={{ ...embed, tone: embed.tone ?? "inline" }}
                    initialTours={initialTours}
                  />
                ))}
              </div>
            ) : null}
          </ContentReadingLayout>

          {!post.noIndex ? (
            <BlogPostNav
              prev={adjacentPosts.prev}
              next={adjacentPosts.next}
              className="mt-10"
            />
          ) : null}

          {!post.noIndex && relatedPosts.length > 0 ? (
            <BlogRelatedPosts posts={relatedPosts} className="mt-10" />
          ) : null}

          {!post.noIndex ? <BlogEngagementCta post={post} className="mt-8" /> : null}
        </div>
      </div>
    </>
  );
}
