import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  sky: "#74acdf",
  skyDark: "#5a8fc4",
  patagonia: "#2d4a3e",
  charcoal: "#1a1a1a",
  slate: "#64748b",
  border: "#e5e7eb",
  muted: "#f8fafc",
  white: "#ffffff",
  red: "#dc2626",
  amber: "#d97706",
};

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "TourPdfSans",
    fontSize: 10,
    lineHeight: 1.45,
    color: pdfColors.charcoal,
    backgroundColor: pdfColors.white,
    paddingTop: 36,
    paddingBottom: 52,
    paddingHorizontal: 40,
  },
  watermark: {
    position: "absolute",
    top: "42%",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 42,
    color: "#eef2f7",
    transform: "rotate(-24deg)",
    fontWeight: 700,
  },
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: pdfColors.sky,
  },
  brandName: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.patagonia,
  },
  brandDomain: {
    fontSize: 9,
    color: pdfColors.skyDark,
    marginTop: 2,
  },
  securityBadge: {
    borderWidth: 1,
    borderColor: pdfColors.sky,
    backgroundColor: "#f0f7fd",
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 8,
    maxWidth: 150,
  },
  securityBadgeTitle: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.patagonia,
  },
  securityBadgeText: {
    fontSize: 7,
    color: pdfColors.slate,
    marginTop: 2,
  },
  heroImage: {
    width: "100%",
    height: 180,
    objectFit: "cover",
    borderRadius: 8,
    marginBottom: 14,
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    color: pdfColors.charcoal,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 11,
    color: pdfColors.slate,
    marginBottom: 14,
  },
  factsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  factPill: {
    backgroundColor: pdfColors.muted,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: pdfColors.border,
    minWidth: "30%",
    flexGrow: 1,
  },
  factLabel: {
    fontSize: 7,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: pdfColors.slate,
    marginBottom: 2,
  },
  factValue: {
    fontSize: 10,
    fontWeight: 600,
    color: pdfColors.charcoal,
  },
  docMetaBox: {
    backgroundColor: pdfColors.muted,
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: pdfColors.border,
  },
  docMetaLine: {
    fontSize: 8,
    color: pdfColors.slate,
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: pdfColors.patagonia,
    marginTop: 8,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
  },
  paragraph: {
    fontSize: 10,
    color: pdfColors.charcoal,
    marginBottom: 8,
  },
  bulletList: {
    marginBottom: 8,
  },
  bulletItem: {
    flexDirection: "row",
    marginBottom: 3,
  },
  bulletDot: {
    width: 10,
    fontSize: 10,
    color: pdfColors.skyDark,
  },
  bulletText: {
    flex: 1,
    fontSize: 9,
    color: pdfColors.charcoal,
  },
  dayCard: {
    marginBottom: 14,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: 8,
    overflow: "hidden",
  },
  dayHeader: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: pdfColors.patagonia,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  dayNumber: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: pdfColors.white,
    color: pdfColors.patagonia,
    fontSize: 10,
    fontWeight: 700,
    textAlign: "center",
    lineHeight: 22,
    marginRight: 8,
  },
  dayTitle: {
    flex: 1,
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.white,
  },
  dayBody: {
    padding: 10,
  },
  dayImagesRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 8,
    marginBottom: 4,
  },
  dayImage: {
    width: 120,
    height: 72,
    objectFit: "cover",
    borderRadius: 4,
  },
  dayMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  dayMetaBox: {
    flexGrow: 1,
    minWidth: "30%",
    backgroundColor: pdfColors.muted,
    borderRadius: 6,
    padding: 6,
  },
  dayMetaLabel: {
    fontSize: 7,
    fontWeight: 600,
    color: pdfColors.slate,
    marginBottom: 3,
    textTransform: "uppercase",
  },
  dayMetaText: {
    fontSize: 8,
    color: pdfColors.charcoal,
  },
  twoColumns: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 8,
  },
  column: {
    flex: 1,
  },
  placeCard: {
    marginBottom: 8,
    padding: 8,
    backgroundColor: pdfColors.muted,
    borderRadius: 6,
  },
  placeTitle: {
    fontSize: 10,
    fontWeight: 600,
    marginBottom: 3,
  },
  placeDescription: {
    fontSize: 8,
    color: pdfColors.slate,
  },
  footer: {
    position: "absolute",
    left: 40,
    right: 40,
    bottom: 18,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  footerLeft: {
    flex: 1,
    paddingRight: 12,
  },
  footerBrand: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.patagonia,
  },
  footerNote: {
    fontSize: 7,
    color: pdfColors.slate,
    marginTop: 2,
  },
  footerRight: {
    fontSize: 7,
    color: pdfColors.slate,
    textAlign: "right",
  },
  disclaimer: {
    fontSize: 7,
    color: pdfColors.slate,
    marginTop: 12,
    padding: 8,
    backgroundColor: pdfColors.muted,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: pdfColors.border,
  },
});
