import type { AdminNavItem, AdminNavSectionId } from "@/types/admin";

export const ADMIN_NAV_SECTION_LABELS: Record<AdminNavSectionId, string> = {
  dashboard: "Обзор",
  operations: "Заявки и бронирования",
  marketplace: "Каталог и партнёры",
  content: "Контент",
  modules: "Модули",
  ingestion: "Источники контента",
  marketing: "Продвижение",
  users: "Пользователи и доступ",
  analytics: "Аналитика",
  system: "Система",
};

export const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  {
    id: "dashboard",
    section: "dashboard",
    href: "/admin",
    label: "Панель",
    capability: "dashboard.view",
  },
  {
    id: "operations-hub",
    section: "operations",
    href: "/admin/operations",
    label: "Операции",
    description: "Командный центр и приоритеты",
    capability: "dashboard.view",
  },
  {
    id: "operations-leads",
    section: "operations",
    href: "/admin/operations/leads",
    label: "Лиды и заявки",
    description: "Подписки, контакты, консультации",
    capability: "operations.leads",
  },
  {
    id: "operations-privacy",
    section: "operations",
    href: "/admin/operations/privacy-requests",
    label: "Запросы на удаление",
    description: "GDPR: очередь удаления данных",
    capability: "operations.leads",
  },
  {
    id: "operations-bookings",
    section: "operations",
    href: "/admin/operations/bookings",
    label: "Бронирования",
    capability: "operations.bookings",
  },
  {
    id: "operations-waitlist",
    section: "operations",
    href: "/admin/operations/waitlist",
    label: "Лист ожидания",
    description: "Связаться с путешественниками и предложить место",
    capability: "operations.bookings",
  },
  {
    id: "operations-email",
    section: "operations",
    href: "/admin/operations/email",
    label: "Очередь писем",
    description: "Повторить доставку и разобрать ошибки",
    capability: "operations.email",
  },
  {
    id: "operations-communications-commerce",
    section: "operations",
    href: "/admin/operations/communications-commerce",
    label: "Готовность подключений",
    description: "Письма и платежи без показа секретов",
    capability: "dashboard.view",
  },
  {
    id: "operations-payments",
    section: "operations",
    href: "/admin/operations/payments",
    label: "Платежи",
    capability: "finance.view",
  },
  {
    id: "operations-reconciliation",
    section: "operations",
    href: "/admin/operations/reconciliation",
    label: "Сверка платежей",
    capability: "finance.view",
  },
  {
    id: "operations-shop",
    section: "operations",
    href: "/admin/operations/shop-orders",
    label: "Заказы магазина",
    capability: "operations.shop",
  },
  {
    id: "marketplace-tours",
    section: "marketplace",
    href: "/admin/marketplace/tours",
    label: "Туры",
    capability: "marketplace.tours",
  },
  {
    id: "marketplace-apartments",
    section: "marketplace",
    href: "/admin/marketplace/apartments",
    label: "Апартаменты",
    description: "Объекты, календарь и публикация",
    capability: "marketplace.moderation",
  },
  {
    id: "marketplace-mobility",
    section: "marketplace",
    href: "/admin/marketplace/mobility",
    label: "Авто и трансферы",
    description: "Поставщики, транспорт и модерация",
    capability: "marketplace.moderation",
  },
  {
    id: "marketplace-excursions",
    section: "marketplace",
    href: "/admin/marketplace/excursions",
    label: "Экскурсии",
    description: "Tripster / Sputnik8",
    capability: "marketplace.excursions",
  },
  {
    id: "marketplace-organizers",
    section: "marketplace",
    href: "/admin/marketplace/organizers",
    label: "Организаторы",
    description: "Анкеты и допуск в кабинет",
    capability: "marketplace.moderation",
  },
  {
    id: "marketplace-experts",
    section: "marketplace",
    href: "/admin/marketplace/experts",
    label: "Эксперты",
    description: "Локальные гиды и консультанты",
    capability: "marketplace.moderation",
  },
  {
    id: "marketplace-moderation",
    section: "marketplace",
    href: "/admin/marketplace/moderation",
    label: "Модерация",
    capability: "marketplace.moderation",
  },
  {
    id: "content-documents",
    section: "content",
    href: "/admin/content/documents",
    label: "Контент и страницы",
    capability: "content.edit",
  },
  {
    id: "content-knowledge",
    section: "content",
    href: "/admin/content/knowledge",
    label: "База знаний",
    description: "Отбор материалов и подготовка статей",
    capability: "content.edit",
  },
  {
    id: "content-forum",
    section: "content",
    href: "/admin/content/forum",
    label: "Форум",
    description: "Разделы, закрепление и закрытие тем",
    capability: "marketplace.moderation",
  },
  {
    id: "content-shop",
    section: "content",
    href: "/admin/content/shop",
    label: "Товары магазина",
    description: "Каталог, цены, остатки и публикация",
    capability: "operations.shop",
  },
  {
    id: "content-map",
    section: "content",
    href: "/admin/content/map",
    label: "Редактор карты",
    description: "Объекты, масштаб и источники",
    capability: "content.edit",
  },
  {
    id: "content-media",
    section: "content",
    href: "/admin/media",
    label: "Медиатека",
    description: "Файлы, подписи, источники и использование",
    capability: "content.edit",
  },
  {
    id: "content-social-feed",
    section: "content",
    href: "/admin/content/social-feed",
    label: "Социальная лента",
    description: "Instagram: источники, публикации, размещения",
    capability: "content.edit",
  },
  {
    id: "content-translations",
    section: "content",
    href: "/admin/content/translations",
    label: "Переводы",
    description: "Покрытие ES/EN и очереди перевода",
    capability: "content.edit",
  },
  {
    id: "content-freshness",
    section: "content",
    href: "/admin/content-freshness",
    label: "Актуальность",
    description: "Контроль сроков проверки материалов",
    capability: "content.edit",
  },
  {
    id: "modules-overview",
    section: "modules",
    href: "/admin/modules",
    label: "Все модули",
    description: "Публичные URL, меню, поиск, sitemap и зависимости",
    capability: "system.settings",
  },
  {
    id: "ingestion-overview",
    section: "ingestion",
    href: "/admin/ingestion",
    label: "Состояние системы",
    description: "Источники, очередь и последние запуски",
    capability: "sources.view",
  },
  {
    id: "ingestion-sources",
    section: "ingestion",
    href: "/admin/ingestion/sources",
    label: "Источники",
    description: "Telegram, сайты, RSS и YouTube",
    capability: "sources.view",
  },
  {
    id: "ingestion-runs",
    section: "ingestion",
    href: "/admin/ingestion/runs",
    label: "Запуски и очередь",
    capability: "ingestion_runs.view",
  },
  {
    id: "ingestion-moderation",
    section: "ingestion",
    href: "/admin/ingestion/moderation",
    label: "Разбор материалов",
    description: "Отбор, правка и передача в CMS",
    capability: "moderation.view",
  },
  {
    id: "ingestion-prompts",
    section: "ingestion",
    href: "/admin/ingestion/prompts",
    label: "Правила анализа",
    capability: "prompts.view",
  },
  {
    id: "users-list",
    section: "users",
    href: "/admin/users",
    label: "Пользователи",
    capability: "users.view",
  },
  {
    id: "analytics-overview",
    section: "analytics",
    href: "/admin/analytics",
    label: "Сводка",
    capability: "analytics.view",
  },
  {
    id: "analytics-funnels",
    section: "analytics",
    href: "/admin/analytics/funnels",
    label: "Воронки",
    description: "Воронка, когорты и экспорт",
    capability: "analytics.view",
  },
  {
    id: "marketing-content-factory",
    section: "marketing",
    href: "/admin/marketing/content-factory",
    label: "Контент-завод",
    description: "План, публикации и сообщения из соцсетей",
    capability: "content.edit",
  },
  {
    id: "marketing-search-visibility",
    section: "marketing",
    href: "/admin/marketing/search-visibility",
    label: "Поиск и SEO",
    description: "Запросы, позиции и точки роста",
    capability: "analytics.view",
  },
  {
    id: "marketing-email-templates",
    section: "marketing",
    href: "/admin/marketing/email-templates",
    label: "Шаблоны писем",
    description: "Версии, предпросмотр и безопасная публикация",
    capability: "system.settings",
  },
  {
    id: "system-redirects",
    section: "content",
    href: "/admin/system/redirects",
    label: "Редиректы",
    description: "301/302 для переноса URL",
    capability: "system.settings",
  },
  {
    id: "system-settings",
    section: "system",
    href: "/admin/system/settings",
    label: "Настройки сайта",
    capability: "system.settings",
  },
  {
    id: "system-commercial-plans",
    section: "system",
    href: "/admin/system/commercial-plans",
    label: "Тарифы и возможности",
    description: "Планы, лимиты и доступ организаторов",
    capability: "system.settings",
  },
  {
    id: "system-feature-flags",
    section: "system",
    href: "/admin/feature-flags",
    label: "Флаги функций",
    description: "Rollout и A/B-эксперименты",
    capability: "system.settings",
  },
  {
    id: "system-api-keys",
    section: "system",
    href: "/admin/system/api-keys",
    label: "API-ключи",
    description: "Публичное API v1 для партнёров",
    capability: "system.settings",
  },
  {
    id: "system-staff",
    section: "system",
    href: "/admin/system/staff",
    label: "Команда",
    description: "Роли и доступ администраторов",
    capability: "users.manage",
  },
  {
    id: "system-audit",
    section: "system",
    href: "/admin/system/audit",
    label: "Журнал действий",
    capability: "system.audit",
  },
];

export function filterAdminNavItems(
  capabilities: readonly string[],
  options?: { includeComingSoon?: boolean }
): AdminNavItem[] {
  const includeComingSoon = options?.includeComingSoon ?? false;
  return ADMIN_NAV_ITEMS.filter((item) => {
    if (item.comingSoon && !includeComingSoon) return false;
    return (
      capabilities.includes("*") ||
      capabilities.includes(item.capability)
    );
  });
}

export function groupAdminNavItems(items: AdminNavItem[]): Map<AdminNavSectionId, AdminNavItem[]> {
  const groups = new Map<AdminNavSectionId, AdminNavItem[]>();
  for (const item of items) {
    const list = groups.get(item.section) ?? [];
    list.push(item);
    groups.set(item.section, list);
  }
  return groups;
}
